/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateContactSupportDto } from '../../models/create-contact-support-dto';
import { CreateContactSupportResponse } from '../../models/create-contact-support-response';

export interface ContactSupportControllerCreate$Params {
      body: CreateContactSupportDto
}

export function contactSupportControllerCreate(http: HttpClient, rootUrl: string, params: ContactSupportControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<CreateContactSupportResponse>> {
  const rb = new RequestBuilder(rootUrl, contactSupportControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreateContactSupportResponse>;
    })
  );
}

contactSupportControllerCreate.PATH = '/api/v1/contact-support';
