/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContactSupportListResponse } from '../../models/contact-support-list-response';

export interface ContactSupportControllerList$Params {
  page?: number;
  limit?: number;
  readed?: 'true' | 'false';

/**
 * Include soft-deleted requests (Laravel `withTrashed()`).
 */
  withTrashed?: (boolean | 'true' | 'false');

/**
 * Return ONLY soft-deleted requests. Cannot be combined with `withTrashed`.
 */
  onlyTrashed?: (boolean | 'true' | 'false');

/**
 * Filter by creation date (inclusive start).
 */
  start_date?: string;

/**
 * Filter by creation date (inclusive end).
 */
  end_date?: string;
}

export function contactSupportControllerList(http: HttpClient, rootUrl: string, params?: ContactSupportControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<ContactSupportListResponse>> {
  const rb = new RequestBuilder(rootUrl, contactSupportControllerList.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('readed', params.readed, {});
    rb.query('withTrashed', params.withTrashed, {});
    rb.query('onlyTrashed', params.onlyTrashed, {});
    rb.query('start_date', params.start_date, {});
    rb.query('end_date', params.end_date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContactSupportListResponse>;
    })
  );
}

contactSupportControllerList.PATH = '/api/v1/contact-support';
