/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ContactSupportControllerExport$Csv$Params {
  format?: 'csv' | 'pdf';
  readed?: 'true' | 'false';

/**
 * Include soft-deleted requests in the export.
 */
  withTrashed?: (boolean | 'true' | 'false');

/**
 * Export ONLY soft-deleted requests. Cannot be combined with `withTrashed`. Requires `Action.Restore`.
 */
  onlyTrashed?: (boolean | 'true' | 'false');

/**
 * Filter by creation date (inclusive start). Format: YYYY-MM-DD.
 */
  start_date?: string;

/**
 * Filter by creation date (inclusive end). Format: YYYY-MM-DD.
 */
  end_date?: string;
}

export function contactSupportControllerExport$Csv(http: HttpClient, rootUrl: string, params?: ContactSupportControllerExport$Csv$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, contactSupportControllerExport$Csv.PATH, 'get');
  if (params) {
    rb.query('format', params.format, {});
    rb.query('readed', params.readed, {});
    rb.query('withTrashed', params.withTrashed, {});
    rb.query('onlyTrashed', params.onlyTrashed, {});
    rb.query('start_date', params.start_date, {});
    rb.query('end_date', params.end_date, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/csv', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

contactSupportControllerExport$Csv.PATH = '/api/v1/contact-support/export';
