/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateAppointmentResponse } from '../../models/create-appointment-response';
import { PublicCreateAppointmentDto } from '../../models/public-create-appointment-dto';

export interface PublicAppointmentsControllerSubmit$Params {
      body: PublicCreateAppointmentDto
}

export function publicAppointmentsControllerSubmit(http: HttpClient, rootUrl: string, params: PublicAppointmentsControllerSubmit$Params, context?: HttpContext): Observable<StrictHttpResponse<CreateAppointmentResponse>> {
  const rb = new RequestBuilder(rootUrl, publicAppointmentsControllerSubmit.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreateAppointmentResponse>;
    })
  );
}

publicAppointmentsControllerSubmit.PATH = '/api/v1/public/appointments';
