/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserPermissionResponseDto } from '../../models/user-permission-response-dto';

export interface UserPermissionsControllerList$Params {
  userId: string;
}

export function userPermissionsControllerList(http: HttpClient, rootUrl: string, params: UserPermissionsControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserPermissionResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, userPermissionsControllerList.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserPermissionResponseDto>>;
    })
  );
}

userPermissionsControllerList.PATH = '/api/v1/users/{userId}/permissions';
