/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpsertUserPermissionDto } from '../../models/upsert-user-permission-dto';
import { UserPermissionResponseDto } from '../../models/user-permission-response-dto';

export interface UserPermissionsControllerUpsert$Params {
  userId: string;
      body: UpsertUserPermissionDto
}

export function userPermissionsControllerUpsert(http: HttpClient, rootUrl: string, params: UserPermissionsControllerUpsert$Params, context?: HttpContext): Observable<StrictHttpResponse<UserPermissionResponseDto>> {
  const rb = new RequestBuilder(rootUrl, userPermissionsControllerUpsert.PATH, 'post');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserPermissionResponseDto>;
    })
  );
}

userPermissionsControllerUpsert.PATH = '/api/v1/users/{userId}/permissions';
