/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UsersControllerCheckEmail$Params {
  value: string;
  excludeId?: string;
}

export function usersControllerCheckEmail(http: HttpClient, rootUrl: string, params: UsersControllerCheckEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'exists'?: boolean;
}>> {
  const rb = new RequestBuilder(rootUrl, usersControllerCheckEmail.PATH, 'get');
  if (params) {
    rb.query('value', params.value, {});
    rb.query('excludeId', params.excludeId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'exists'?: boolean;
      }>;
    })
  );
}

usersControllerCheckEmail.PATH = '/api/v1/users/check/email';
