/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface UsersControllerExport$Params {

/**
 * Export ONLY suspended users (audit report of deactivated accounts). Requires the `Restore USER` ability.
 */
  onlyTrashed?: boolean;

/**
 * Include suspended users in the export.
 */
  withTrashed?: boolean;
}

export function usersControllerExport(http: HttpClient, rootUrl: string, params?: UsersControllerExport$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, usersControllerExport.PATH, 'get');
  if (params) {
    rb.query('onlyTrashed', params.onlyTrashed, {});
    rb.query('withTrashed', params.withTrashed, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

usersControllerExport.PATH = '/api/v1/users/export';
