/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserListResponse } from '../../models/user-list-response';

export interface UsersControllerFindAll$Params {
  page?: number;
  limit?: number;
  search?: string;

/**
 * Include suspended (soft-deleted) users alongside active ones. Laravel-style `withTrashed()`.
 */
  withTrashed?: (boolean | 'true' | 'false');

/**
 * Return ONLY suspended users — useful for audit reports. Laravel-style `onlyTrashed()`. Cannot be combined with `withTrashed`. Requires the `Restore USER` ability.
 */
  onlyTrashed?: (boolean | 'true' | 'false');

/**
 * Filter by creation date (inclusive start).
 */
  start_date?: string;

/**
 * Filter by creation date (inclusive end).
 */
  end_date?: string;
}

export function usersControllerFindAll(http: HttpClient, rootUrl: string, params?: UsersControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<UserListResponse>> {
  const rb = new RequestBuilder(rootUrl, usersControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('search', params.search, {});
    rb.query('withTrashed', params.withTrashed, {});
    rb.query('onlyTrashed', params.onlyTrashed, {});
    rb.query('start_date', params.start_date, {});
    rb.query('end_date', params.end_date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserListResponse>;
    })
  );
}

usersControllerFindAll.PATH = '/api/v1/users';
