/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MessageResponse } from '../../models/message-response';
import { RequestPasswordChangeDto } from '../../models/request-password-change-dto';

export interface UsersControllerRequestPasswordChange$Params {
      body: RequestPasswordChangeDto
}

export function usersControllerRequestPasswordChange(http: HttpClient, rootUrl: string, params: UsersControllerRequestPasswordChange$Params, context?: HttpContext): Observable<StrictHttpResponse<MessageResponse>> {
  const rb = new RequestBuilder(rootUrl, usersControllerRequestPasswordChange.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MessageResponse>;
    })
  );
}

usersControllerRequestPasswordChange.PATH = '/api/v1/users/request-password-change';
