/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserResponse } from '../../models/user-response';

export interface UsersControllerFindOne$Params {
  id: string;

/**
 * When `true`, return the user even if it has been suspended (soft-deleted). Without it the endpoint behaves like `Model::find()` and returns 404 for suspended rows.
 */
  withTrashed?: boolean;
}

export function usersControllerFindOne(http: HttpClient, rootUrl: string, params: UsersControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
  const rb = new RequestBuilder(rootUrl, usersControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('withTrashed', params.withTrashed, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserResponse>;
    })
  );
}

usersControllerFindOne.PATH = '/api/v1/users/{id}';
