/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CampaignExportListItemResponse } from '../../models/campaign-export-list-item-response';

export interface CampaignsControllerListExports$Params {
  offset?: number;
  limit?: number;
}

export function campaignsControllerListExports(http: HttpClient, rootUrl: string, params?: CampaignsControllerListExports$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CampaignExportListItemResponse>>> {
  const rb = new RequestBuilder(rootUrl, campaignsControllerListExports.PATH, 'get');
  if (params) {
    rb.query('offset', params.offset, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CampaignExportListItemResponse>>;
    })
  );
}

campaignsControllerListExports.PATH = '/api/v1/campaigns/exports';
