/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CampaignExportListItemResponse } from '../../models/campaign-export-list-item-response';

export interface CampaignsControllerListCampaigns$Params {

/**
 * Filter by creation date (ISO 8601)
 */
  end_date?: string;

/**
 * Filter by creation date (ISO 8601)
 */
  start_date?: string;
  onlyTrashed?: boolean;
  withTrashed?: boolean;
  status?: 'pending' | 'processing' | 'completed' | 'failed' | 'partial';
  offset?: number;
  limit?: number;
}

export function campaignsControllerListCampaigns(http: HttpClient, rootUrl: string, params?: CampaignsControllerListCampaigns$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CampaignExportListItemResponse>>> {
  const rb = new RequestBuilder(rootUrl, campaignsControllerListCampaigns.PATH, 'get');
  if (params) {
    rb.query('end_date', params.end_date, {});
    rb.query('start_date', params.start_date, {});
    rb.query('onlyTrashed', params.onlyTrashed, {});
    rb.query('withTrashed', params.withTrashed, {});
    rb.query('status', params.status, {});
    rb.query('offset', params.offset, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CampaignExportListItemResponse>>;
    })
  );
}

campaignsControllerListCampaigns.PATH = '/api/v1/campaigns';
