/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BulkDeleteCampaignsBody } from '../../models/bulk-delete-campaigns-body';

export interface CampaignsControllerBulkDeleteCampaigns$Params {
      body: BulkDeleteCampaignsBody
}

export function campaignsControllerBulkDeleteCampaigns(http: HttpClient, rootUrl: string, params: CampaignsControllerBulkDeleteCampaigns$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, campaignsControllerBulkDeleteCampaigns.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

campaignsControllerBulkDeleteCampaigns.PATH = '/api/v1/campaigns/bulk-delete';
