/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface BlogCategoryControllerExport$Params {

/**
 * Filter by createdAt <= end_date (inclusive).
 */
  end_date?: string;

/**
 * Filter by createdAt >= start_date (inclusive).
 */
  start_date?: string;
  onlyTrashed?: boolean;
  withTrashed?: boolean;
  format: 'csv' | 'xlsx' | 'pdf';
}

export function blogCategoryControllerExport(http: HttpClient, rootUrl: string, params: BlogCategoryControllerExport$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, blogCategoryControllerExport.PATH, 'get');
  if (params) {
    rb.query('end_date', params.end_date, {});
    rb.query('start_date', params.start_date, {});
    rb.query('onlyTrashed', params.onlyTrashed, {});
    rb.query('withTrashed', params.withTrashed, {});
    rb.query('format', params.format, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

blogCategoryControllerExport.PATH = '/api/v1/blog-categories/export';
