/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BlogCategoryResponse } from '../../models/blog-category-response';

export interface BlogCategoryControllerFindAll$Params {

/**
 * Filter by createdAt <= end_date (inclusive).
 */
  end_date?: string;

/**
 * Filter by createdAt >= start_date (inclusive).
 */
  start_date?: string;

/**
 * Return ONLY soft-deleted categories. Cannot be combined with `withTrashed`. Requires Action.Restore (use GET /blog-categories/trash).
 */
  onlyTrashed?: boolean;

/**
 * Include soft-deleted categories (Laravel `withTrashed()`).
 */
  withTrashed?: boolean;
  skip?: number;
  limit?: number;
}

export function blogCategoryControllerFindAll(http: HttpClient, rootUrl: string, params?: BlogCategoryControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BlogCategoryResponse>>> {
  const rb = new RequestBuilder(rootUrl, blogCategoryControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('end_date', params.end_date, {});
    rb.query('start_date', params.start_date, {});
    rb.query('onlyTrashed', params.onlyTrashed, {});
    rb.query('withTrashed', params.withTrashed, {});
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BlogCategoryResponse>>;
    })
  );
}

blogCategoryControllerFindAll.PATH = '/api/v1/blog-categories';
