/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BlogCategoryResponse } from '../../models/blog-category-response';
import { Function } from '../../models/function';

export interface BlogCategoryControllerUpdate$Params {
  id: string;
      body: Function
}

export function blogCategoryControllerUpdate(http: HttpClient, rootUrl: string, params: BlogCategoryControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<BlogCategoryResponse>> {
  const rb = new RequestBuilder(rootUrl, blogCategoryControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BlogCategoryResponse>;
    })
  );
}

blogCategoryControllerUpdate.PATH = '/api/v1/blog-categories/{id}';
