/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BlogCategoryResponse } from '../../models/blog-category-response';

export interface BlogCategoryControllerFindOne$Params {
  id: string;

/**
 * When `true`, return the category even if it has been soft-deleted.
 */
  withTrashed?: boolean;
}

export function blogCategoryControllerFindOne(http: HttpClient, rootUrl: string, params: BlogCategoryControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<BlogCategoryResponse>> {
  const rb = new RequestBuilder(rootUrl, blogCategoryControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('withTrashed', params.withTrashed, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BlogCategoryResponse>;
    })
  );
}

blogCategoryControllerFindOne.PATH = '/api/v1/blog-categories/{id}';
