/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BackupTriggeredResponse } from '../../models/backup-triggered-response';

export interface BackupControllerTrigger$Params {
}

export function backupControllerTrigger(http: HttpClient, rootUrl: string, params?: BackupControllerTrigger$Params, context?: HttpContext): Observable<StrictHttpResponse<BackupTriggeredResponse>> {
  const rb = new RequestBuilder(rootUrl, backupControllerTrigger.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BackupTriggeredResponse>;
    })
  );
}

backupControllerTrigger.PATH = '/api/v1/backups/run';
