/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface BackupControllerExport$Csv$Params {
  format?: 'csv' | 'xlsx' | 'pdf';
}

export function backupControllerExport$Csv(http: HttpClient, rootUrl: string, params?: BackupControllerExport$Csv$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, backupControllerExport$Csv.PATH, 'get');
  if (params) {
    rb.query('format', params.format, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/csv', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

backupControllerExport$Csv.PATH = '/api/v1/backups/export';
