/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppointmentListResponse } from '../../models/appointment-list-response';

export interface AppointmentsControllerFindAll$Params {
  statusLead?: 'New' | 'Called' | 'Pending' | 'Declined';
  city?: string;
  state?: string;
  country?: string;
  owner?: string;
  page?: number;
  limit?: number;

/**
 * Include soft-deleted appointments alongside active ones (Laravel `withTrashed()`).
 */
  withTrashed?: (boolean | 'true' | 'false');

/**
 * Return ONLY soft-deleted appointments. Cannot be combined with `withTrashed`. Requires `Action.Restore`.
 */
  onlyTrashed?: (boolean | 'true' | 'false');

/**
 * Filter appointments created on or after this date (inclusive).
 */
  start_date?: string;

/**
 * Filter appointments created on or before this date (inclusive).
 */
  end_date?: string;
}

export function appointmentsControllerFindAll(http: HttpClient, rootUrl: string, params?: AppointmentsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<AppointmentListResponse>> {
  const rb = new RequestBuilder(rootUrl, appointmentsControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('statusLead', params.statusLead, {});
    rb.query('city', params.city, {});
    rb.query('state', params.state, {});
    rb.query('country', params.country, {});
    rb.query('owner', params.owner, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('withTrashed', params.withTrashed, {});
    rb.query('onlyTrashed', params.onlyTrashed, {});
    rb.query('start_date', params.start_date, {});
    rb.query('end_date', params.end_date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AppointmentListResponse>;
    })
  );
}

appointmentsControllerFindAll.PATH = '/api/v1/appointments';
