/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppointmentResponse } from '../../models/appointment-response';

export interface AppointmentsControllerFindOne$Params {
  id: string;

/**
 * When `true`, return the appointment even if it has been soft-deleted. Without it, soft-deleted rows yield 404.
 */
  withTrashed?: boolean;
}

export function appointmentsControllerFindOne(http: HttpClient, rootUrl: string, params: AppointmentsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<AppointmentResponse>> {
  const rb = new RequestBuilder(rootUrl, appointmentsControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('withTrashed', params.withTrashed, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AppointmentResponse>;
    })
  );
}

appointmentsControllerFindOne.PATH = '/api/v1/appointments/{id}';
