/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BulkIdsDto } from '../../models/bulk-ids-dto';

export interface AppointmentsControllerBulkRestore$Params {
      body: BulkIdsDto
}

export function appointmentsControllerBulkRestore(http: HttpClient, rootUrl: string, params: AppointmentsControllerBulkRestore$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, appointmentsControllerBulkRestore.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

appointmentsControllerBulkRestore.PATH = '/api/v1/appointments/bulk-restore';
