/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AppointmentsControllerExport$Pdf$Params {
  format?: 'csv' | 'xlsx' | 'pdf';
  statusLead?: 'New' | 'Called' | 'Pending' | 'Declined';
  city?: string;
  state?: string;
  country?: string;
  owner?: string;

/**
 * Include soft-deleted appointments in the export.
 */
  withTrashed?: (boolean | 'true' | 'false');

/**
 * Export ONLY soft-deleted appointments. Cannot be combined with `withTrashed`. Requires `Action.Restore`.
 */
  onlyTrashed?: (boolean | 'true' | 'false');

/**
 * Filter appointments created on or after this date (inclusive).
 */
  start_date?: string;

/**
 * Filter appointments created on or before this date (inclusive).
 */
  end_date?: string;
}

export function appointmentsControllerExport$Pdf(http: HttpClient, rootUrl: string, params?: AppointmentsControllerExport$Pdf$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, appointmentsControllerExport$Pdf.PATH, 'get');
  if (params) {
    rb.query('format', params.format, {});
    rb.query('statusLead', params.statusLead, {});
    rb.query('city', params.city, {});
    rb.query('state', params.state, {});
    rb.query('country', params.country, {});
    rb.query('owner', params.owner, {});
    rb.query('withTrashed', params.withTrashed, {});
    rb.query('onlyTrashed', params.onlyTrashed, {});
    rb.query('start_date', params.start_date, {});
    rb.query('end_date', params.end_date, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/pdf', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

appointmentsControllerExport$Pdf.PATH = '/api/v1/appointments/export';
