/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RolesControllerExport$Params {
  page?: number;
  limit?: number;
  search?: string;
  withTrashed?: (boolean | 'true' | 'false');
  onlyTrashed?: (boolean | 'true' | 'false');
  format: 'csv' | 'xlsx' | 'pdf';
}

export function rolesControllerExport(http: HttpClient, rootUrl: string, params: RolesControllerExport$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, rolesControllerExport.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('search', params.search, {});
    rb.query('withTrashed', params.withTrashed, {});
    rb.query('onlyTrashed', params.onlyTrashed, {});
    rb.query('format', params.format, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

rolesControllerExport.PATH = '/api/v1/roles/export';
