/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AttachPermissionDto } from '../../models/attach-permission-dto';
import { RoleResponseDto } from '../../models/role-response-dto';

export interface RolesControllerAttachPermission$Params {
  id: string;
      body: AttachPermissionDto
}

export function rolesControllerAttachPermission(http: HttpClient, rootUrl: string, params: RolesControllerAttachPermission$Params, context?: HttpContext): Observable<StrictHttpResponse<RoleResponseDto>> {
  const rb = new RequestBuilder(rootUrl, rolesControllerAttachPermission.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RoleResponseDto>;
    })
  );
}

rolesControllerAttachPermission.PATH = '/api/v1/roles/{id}/permissions';
