/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoleResponseDto } from '../../models/role-response-dto';

export interface RolesControllerFindAll$Params {
  page?: number;
  limit?: number;
  search?: string;

/**
 * Include soft-deleted roles.
 */
  withTrashed?: (boolean | 'true' | 'false');

/**
 * Return only soft-deleted roles.
 */
  onlyTrashed?: (boolean | 'true' | 'false');
}

export function rolesControllerFindAll(http: HttpClient, rootUrl: string, params?: RolesControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoleResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, rolesControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('search', params.search, {});
    rb.query('withTrashed', params.withTrashed, {});
    rb.query('onlyTrashed', params.onlyTrashed, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RoleResponseDto>>;
    })
  );
}

rolesControllerFindAll.PATH = '/api/v1/roles';
