/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoleResponseDto } from '../../models/role-response-dto';

export interface RolesControllerFindTrash$Params {
}

export function rolesControllerFindTrash(http: HttpClient, rootUrl: string, params?: RolesControllerFindTrash$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoleResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, rolesControllerFindTrash.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RoleResponseDto>>;
    })
  );
}

rolesControllerFindTrash.PATH = '/api/v1/roles/trash';
