/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoleResponseDto } from '../../models/role-response-dto';

export interface RolesControllerFindOne$Params {
  id: string;

/**
 * When `true`, return the role even if soft-deleted.
 */
  withTrashed?: (boolean | 'true' | 'false');
}

export function rolesControllerFindOne(http: HttpClient, rootUrl: string, params: RolesControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<RoleResponseDto>> {
  const rb = new RequestBuilder(rootUrl, rolesControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('withTrashed', params.withTrashed, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RoleResponseDto>;
    })
  );
}

rolesControllerFindOne.PATH = '/api/v1/roles/{id}';
