/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface PostsControllerExport$Params {

/**
 * Export format. Defaults to `xlsx`.
 */
  format?: 'csv' | 'xlsx' | 'pdf';
  postStatus?: 'draft' | 'published' | 'scheduled';
  categoryId?: string;
  userId?: string;
  search?: string;

/**
 * Include soft-deleted posts in the export.
 */
  withTrashed?: (boolean | 'true' | 'false');

/**
 * Export ONLY soft-deleted posts. Cannot be combined with `withTrashed`. Requires `Action.Restore`.
 */
  onlyTrashed?: (boolean | 'true' | 'false');

/**
 * Filter by creation date (inclusive start).
 */
  start_date?: string;

/**
 * Filter by creation date (inclusive end).
 */
  end_date?: string;
}

export function postsControllerExport(http: HttpClient, rootUrl: string, params?: PostsControllerExport$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, postsControllerExport.PATH, 'get');
  if (params) {
    rb.query('format', params.format, {});
    rb.query('postStatus', params.postStatus, {});
    rb.query('categoryId', params.categoryId, {});
    rb.query('userId', params.userId, {});
    rb.query('search', params.search, {});
    rb.query('withTrashed', params.withTrashed, {});
    rb.query('onlyTrashed', params.onlyTrashed, {});
    rb.query('start_date', params.start_date, {});
    rb.query('end_date', params.end_date, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

postsControllerExport.PATH = '/api/v1/posts/export';
