/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PostListResponse } from '../../models/post-list-response';

export interface PostsControllerFindAll$Params {
  postStatus?: 'draft' | 'published' | 'scheduled';
  categoryId?: string;
  userId?: string;
  search?: string;
  page?: number;
  limit?: number;

/**
 * Include soft-deleted posts alongside active ones.
 */
  withTrashed?: (boolean | 'true' | 'false');

/**
 * Return ONLY soft-deleted posts. Cannot be combined with `withTrashed`. Requires `Action.Restore`.
 */
  onlyTrashed?: (boolean | 'true' | 'false');

/**
 * Filter by creation date (inclusive start).
 */
  start_date?: string;

/**
 * Filter by creation date (inclusive end).
 */
  end_date?: string;
}

export function postsControllerFindAll(http: HttpClient, rootUrl: string, params?: PostsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<PostListResponse>> {
  const rb = new RequestBuilder(rootUrl, postsControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('postStatus', params.postStatus, {});
    rb.query('categoryId', params.categoryId, {});
    rb.query('userId', params.userId, {});
    rb.query('search', params.search, {});
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('withTrashed', params.withTrashed, {});
    rb.query('onlyTrashed', params.onlyTrashed, {});
    rb.query('start_date', params.start_date, {});
    rb.query('end_date', params.end_date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PostListResponse>;
    })
  );
}

postsControllerFindAll.PATH = '/api/v1/posts';
