/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatePostResponse } from '../../models/create-post-response';

export interface PostsControllerCreate$Params {
  
    /**
     * Post payload. Use generateWithAi for fully automated creation.
     */
    body: string
}

export function postsControllerCreate(http: HttpClient, rootUrl: string, params: PostsControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<CreatePostResponse>> {
  const rb = new RequestBuilder(rootUrl, postsControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreatePostResponse>;
    })
  );
}

postsControllerCreate.PATH = '/api/v1/posts';
