/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GeneratePostPreviewResponse } from '../../models/generate-post-preview-response';

export interface PostsControllerGeneratePreview$Params {
  
    /**
     * AI generation parameters
     */
    body: string
}

export function postsControllerGeneratePreview(http: HttpClient, rootUrl: string, params: PostsControllerGeneratePreview$Params, context?: HttpContext): Observable<StrictHttpResponse<GeneratePostPreviewResponse>> {
  const rb = new RequestBuilder(rootUrl, postsControllerGeneratePreview.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GeneratePostPreviewResponse>;
    })
  );
}

postsControllerGeneratePreview.PATH = '/api/v1/posts/ai/generate-preview';
