/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GenerateSocialIdeasResponse } from '../../models/generate-social-ideas-response';

export interface PostsControllerGenerateSocialPostIdeas$Params {
  
    /**
     * Content idea generation parameters
     */
    body: string
}

export function postsControllerGenerateSocialPostIdeas(http: HttpClient, rootUrl: string, params: PostsControllerGenerateSocialPostIdeas$Params, context?: HttpContext): Observable<StrictHttpResponse<GenerateSocialIdeasResponse>> {
  const rb = new RequestBuilder(rootUrl, postsControllerGenerateSocialPostIdeas.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GenerateSocialIdeasResponse>;
    })
  );
}

postsControllerGenerateSocialPostIdeas.PATH = '/api/v1/posts/social/generate-ideas';
