/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActivityLogResponse } from '../../models/activity-log-response';

export interface ActivityLogControllerFindAll$Params {

/**
 * Filter by date (inclusive end). Format: YYYY-MM-DD.
 */
  end_date?: string;

/**
 * Filter by date (inclusive start). Format: YYYY-MM-DD.
 */
  start_date?: string;
  resourceId?: string;
  action?: string;
  actorId?: string;
  limit?: number;
  page?: number;
}

export function activityLogControllerFindAll(http: HttpClient, rootUrl: string, params?: ActivityLogControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ActivityLogResponse>>> {
  const rb = new RequestBuilder(rootUrl, activityLogControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('end_date', params.end_date, {});
    rb.query('start_date', params.start_date, {});
    rb.query('resourceId', params.resourceId, {});
    rb.query('action', params.action, {});
    rb.query('actorId', params.actorId, {});
    rb.query('limit', params.limit, {});
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ActivityLogResponse>>;
    })
  );
}

activityLogControllerFindAll.PATH = '/api/v1/activity-logs';
