/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActivityLogResponse {
  action: string;
  actorId: string | null;
  correlationId: string | null;
  createdAt: string;
  id: string;
  ipAddress: string | null;
  metadata: ({
[key: string]: any;
}) | null;
  resourceId: string | null;
  resourceType: string | null;
  traceId: string | null;
  userAgent: string | null;
}
