/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AppointmentResponse {
  additionalNote: string | null;
  address: string;
  address2: string | null;
  city: string;
  country: string;
  createdAt: string;
  deletedAt: string | null;
  email: string | null;
  firstName: string;
  followUpCalls: any | null;
  id: string;
  lastName: string;
  latitude: number | null;
  longitude: number | null;
  message: string | null;
  notes: string | null;
  owner: string | null;
  phone: string;
  readed: boolean;
  registrationDate: string | null;
  smsConsent: boolean;
  state: string;
  statusLead: string | null;
  updatedAt: string;
  zipcode: string;
}
