/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AppointmentListResponse {
  data: Array<{
'id': string;
'firstName': string;
'lastName': string;
'phone': string;
'email': string | null;
'address': string;
'address2': string | null;
'city': string;
'state': string;
'zipcode': string;
'country': string;
'message': string | null;
'smsConsent': boolean;
'registrationDate': string | null;
'statusLead': string | null;
'followUpCalls': any | null;
'notes': string | null;
'owner': string | null;
'additionalNote': string | null;
'latitude': number | null;
'longitude': number | null;
'readed': boolean;
'createdAt': string;
'updatedAt': string;
'deletedAt': string | null;
}>;
  limit: number;
  page: number;
  total: number;
}
