/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BackupListResponse {
  data: Array<{
'id': string;
'status': 'PENDING' | 'COMPLETED' | 'FAILED';
'triggeredBy': 'SCHEDULER' | 'MANUAL';
'actorId': string | null;
'objectKey': string | null;
'sizeBytes': number | null;
'checksum': string | null;
'error': string | null;
'startedAt': string;
'completedAt': string | null;
'createdAt': string;
}>;
  limit: number;
  page: number;
  total: number;
}
