/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BackupResponse {
  actorId: string | null;
  checksum: string | null;
  completedAt: string | null;
  createdAt: string;
  error: string | null;
  id: string;
  objectKey: string | null;
  sizeBytes: number | null;
  startedAt: string;
  status: 'PENDING' | 'COMPLETED' | 'FAILED';
  triggeredBy: 'SCHEDULER' | 'MANUAL';
}
