/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BlogCategoryResponse {
  createdAt: string;
  deletedAt: string | null;
  description: string | null;
  id: string;
  image: string | null;
  name: string | null;
  updatedAt: string;
  userId: string;
}
