/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BulkDeleteCampaignsBody {

  /**
   * Array of campaign generation IDs to delete
   */
  ids: Array<string>;
}
