/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CampaignExportStatusResponse {
  companyName: string;
  createdAt: string;
  durationSeconds: number;
  errorMessage: string | null;
  format: string;
  generateImages: boolean;
  id: string;
  language: string;
  location: string;
  niche: string;
  phone: string;
  stageExports: Array<{
'stage': string;
'zipKey': string | null;
'zipUrl': string | null;
'sizeBytes': number | null;
'error': string | null;
'hasAudio': boolean;
'hasImages': boolean;
}>;
  stages: Array<string>;
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'partial';
  updatedAt: string;
  userId: string;
  website: string | null;
}
