/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CampaignExportListItemResponse {
  companyName: string;
  createdAt: string;
  hasErrors: boolean;
  id: string;
  niche: string;
  stagesCompleted: number;
  stagesRequested: number;
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'partial';
}
