/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactSupportListResponse {
  data: Array<{
'id': string;
'firstName': string;
'lastName': string;
'email': string;
'phone': string;
'subject': string;
'message': string;
'smsConsent': boolean;
'readed': boolean;
'createdAt': string;
'updatedAt': string;
'deletedAt': string | null;
}>;
  limit: number;
  page: number;
  total: number;
}
