/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateAppointmentDto {
  additionalNote?: string | null;
  address: string;
  address2?: string | null;
  city: string;
  country: string;
  email?: string | null;
  firstName: string;
  followUpCalls?: any | null;
  lastName: string;
  latitude?: number | null;
  longitude?: number | null;
  message?: string | null;
  notes?: string | null;
  owner?: string | null;
  phone: string;
  registrationDate?: string | null;
  smsConsent?: boolean;
  state: string;
  statusLead?: 'New' | 'Called' | 'Pending' | 'Declined' | 'null';
  zipcode: string;
}
