/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateContactSupportDto {
  email: string;
  firstName: string;
  lastName: string;
  message: string;
  phone: string;
  smsConsent?: boolean;
  subject: string;
}
