/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExportSocialMediaDto {
  end_date?: string;
  format?: 'csv' | 'xlsx' | 'pdf';
  language?: string;
  network?: 'facebook' | 'instagram' | 'tiktok' | 'linkedin' | 'twitter';
  niche?: string;
  start_date?: string;
}
