/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GenerateSocialIdeasResponse {
  content_ideas: Array<{
'id': number;
'title': string;
'angle': string;
'hook': string;
'platform': string;
'estimated_virality': number;
'estimated_roi': number;
'estimated_engagement': string;
'difficulty': string;
'eeat_potential': number;
'why_it_works': string;
'key_trend': string;
'suggested_format': string;
'content_type': string;
}>;
  niche_analysis: {
'target_audience': string;
'audience_demographics': string;
'key_pain_points': Array<string>;
'content_preferences': Array<string>;
'trending_topics': Array<string>;
'tavily_insights': Array<string>;
};
}
