/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GenerateTopicsBody {

  /**
   * AI observations (max 400 characters)
   */
  aiObservations?: string;

  /**
   * City
   */
  city?: string;

  /**
   * Country
   */
  country?: string;

  /**
   * Language code
   */
  language: string;

  /**
   * Location
   */
  location: string;

  /**
   * Business niche
   */
  niche: string;

  /**
   * State
   */
  state?: string;
}
