/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GenerateSocialPostResponse {
  cover_image: {
'main_prompt': string;
'main_image_url': string | null;
'style': string;
'color_palette': Array<string>;
'mood': string;
'key_elements': Array<string>;
};
  eeat_analysis: {
'experience_signals': Array<string>;
'expertise_signals': Array<string>;
'authoritativeness_signals': Array<string>;
'trustworthiness_signals': Array<string>;
};
  id: string;
  metadata: {
'ai_model': string;
'iterations_required': number;
'tavily_searches_performed': number;
'ai_generated_at': string;
};
  optimization_suggestions: Array<string>;
  platform_variations: {
'blog': {
'adapted_content': string;
'character_count': number | null;
'word_count': number | null;
'hashtags': Array<string>;
'image_prompt': string;
'cover_image_url': string | null;
'subject_line': string | null;
'preview_text': string | null;
'is_thread': boolean;
'thread_tweets': Array<string>;
};
'linkedin': {
'adapted_content': string;
'character_count': number | null;
'word_count': number | null;
'hashtags': Array<string>;
'image_prompt': string;
'cover_image_url': string | null;
'subject_line': string | null;
'preview_text': string | null;
'is_thread': boolean;
'thread_tweets': Array<string>;
};
'twitter': {
'adapted_content': string;
'character_count': number | null;
'word_count': number | null;
'hashtags': Array<string>;
'image_prompt': string;
'cover_image_url': string | null;
'subject_line': string | null;
'preview_text': string | null;
'is_thread': boolean;
'thread_tweets': Array<string>;
};
'newsletter': {
'adapted_content': string;
'character_count': number | null;
'word_count': number | null;
'hashtags': Array<string>;
'image_prompt': string;
'cover_image_url': string | null;
'subject_line': string | null;
'preview_text': string | null;
'is_thread': boolean;
'thread_tweets': Array<string>;
};
'facebook': {
'adapted_content': string;
'character_count': number | null;
'word_count': number | null;
'hashtags': Array<string>;
'image_prompt': string;
'cover_image_url': string | null;
'subject_line': string | null;
'preview_text': string | null;
'is_thread': boolean;
'thread_tweets': Array<string>;
};
};
  post_content: {
'headline': string;
'body': string;
'call_to_action': string;
'hashtags': Array<string>;
};
  quality_warning: boolean;
  quality_warning_message: string | null;
  research_sources: Array<{
'title': string;
'url': string;
'snippet': string;
'score': number;
}>;
  scores: {
'human_writing_index': {
'value': number;
'threshold': number;
'passes': boolean;
'factors': Array<string>;
'explanation': string;
};
'human_likeness_score': {
'value': number;
'threshold': number;
'passes': boolean;
'factors': Array<string>;
'explanation': string;
};
'eeat_score': {
'value': number;
'threshold': number;
'passes': boolean;
'factors': Array<string>;
'explanation': string;
};
'virality_score': {
'value': number;
'threshold': number;
'passes': boolean;
'factors': Array<string>;
'explanation': string;
};
'roi_score': {
'value': number;
'threshold': number;
'passes': boolean;
'factors': Array<string>;
'explanation': string;
};
'seo_score': {
'value': number;
'threshold': number;
'passes': boolean;
'factors': Array<string>;
'explanation': string;
};
'ai_detection_risk': {
'value': number;
'label': string;
'explanation': string;
};
'summary': {
'all_pass': boolean;
'overall_average': number;
'ready_to_publish': boolean;
'iterations_required': number;
};
};
  seo_analysis: {
'primary_keyword': string;
'lsi_keywords': Array<string>;
'technical_factors': Array<string>;
'semantic_factors': Array<string>;
'machine_readability': Array<string>;
};
  seo_metadata: {
'meta_title': string;
'meta_description': string;
'og_title': string;
'og_description': string;
'og_image_url': string;
'og_type': string;
'twitter_card': string;
'twitter_title': string;
'twitter_description': string;
'twitter_image_url': string;
'canonical_url': string;
'schema_json_ld': {
[key: string]: any;
};
};
}
