/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GeneratePostDto {
  language?: string;
  networks: {
'facebook'?: boolean;
'instagram'?: boolean;
'tiktok'?: boolean;
'linkedin'?: boolean;
'twitter'?: boolean;
};
  saveToHistory?: boolean;
  topic: {
'title': string;
'description': string;
};
  topicId?: string;
}
