/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GeneratePostPreviewResponse {
  generated_image_url: string | null;
  meta_description: string;
  meta_keywords: string;
  meta_title: string;
  post_content: string;
  post_excerpt: string;
  post_title_slug: string;
  sources: Array<{
'title': string;
'url': string;
'snippet': string;
'score': number;
}>;
}
