/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GenerateCampaignBody {

  /**
   * AI observations (max 400 characters)
   */
  aiObservations?: string;

  /**
   * AI provider
   */
  aiProvider: 'gemini' | 'claude' | 'openai';

  /**
   * City
   */
  city?: string;

  /**
   * Company data ID (UUID)
   */
  companyDataId: string;

  /**
   * Country
   */
  country?: string;

  /**
   * Video duration in seconds
   */
  durationSeconds: 15 | 20;

  /**
   * Video aspect ratio
   */
  format: '9:16' | '16:9' | 'both';

  /**
   * Generate images
   */
  generateImages: boolean;

  /**
   * Language code
   */
  language: string;

  /**
   * Location
   */
  location: string;

  /**
   * Business niche
   */
  niche: string;

  /**
   * Phone number
   */
  phone: string;

  /**
   * Funnel stages (TOFU/MOFU/BOFU/LOYALTY)
   */
  stages: Array<'TOFU' | 'MOFU' | 'BOFU' | 'LOYALTY'>;

  /**
   * State
   */
  state?: string;

  /**
   * Selected topic ID from generate-topics response
   */
  topicId: string;

  /**
   * Website URL
   */
  website?: string;
}
