/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaginatedSocialMediaResponse {
  data: Array<{
'id': string;
'userId': string;
'niche': string;
'topicTitle': string;
'topicDescription': string | null;
'language': string | null;
'networks': {
[key: string]: boolean;
};
'generatedPosts': {
[key: string]: {
'body': string;
'hashtags': Array<string>;
'emojis'?: string;
'hook'?: string;
'image'?: {
'url'?: string;
'r2Key'?: string;
'mimeType'?: string;
};
};
};
'r2Key'?: string | null;
'viralityScore'?: number | null;
'roiScore'?: number | null;
'aiDetectionScore'?: ({
'aiGenerated': number;
'aiParaphrased': number;
'humanWritten': number;
'showsAiSigns': number;
}) | null;
'analysisReportKey'?: string | null;
'analysisReportUrl'?: string | null;
'createdAt': string;
}>;
  limit: number;
  page: number;
  total: number;
}
