/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PostListResponse {
  data: Array<{
'id': string;
'postTitle': string;
'postTitleSlug': string;
'postContent': string;
'postExcerpt': string | null;
'postCoverImage': string | null;
'metaTitle': string | null;
'metaDescription': string | null;
'metaKeywords': string | null;
'categoryId': string | null;
'userId': string | null;
'postStatus': 'draft' | 'published' | 'scheduled';
'scheduledAt': string | null;
'createdAt': string;
'updatedAt': string;
'deletedAt': string | null;
'categoryName'?: string | null;
'userName'?: string | null;
}>;
  limit: number;
  page: number;
  total: number;
}
