/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PostResponse {
  categoryId: string | null;
  categoryName?: string | null;
  createdAt: string;
  deletedAt: string | null;
  id: string;
  metaDescription: string | null;
  metaKeywords: string | null;
  metaTitle: string | null;
  postContent: string;
  postCoverImage: string | null;
  postExcerpt: string | null;
  postStatus: 'draft' | 'published' | 'scheduled';
  postTitle: string;
  postTitleSlug: string;
  scheduledAt: string | null;
  updatedAt: string;
  userId: string | null;
  userName?: string | null;
}
