/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicCreateAppointmentDto {
  address: string;
  address2?: string | null;
  city: string;
  country: string;
  email?: string | null;
  firstName: string;
  lastName: string;
  latitude?: number | null;
  longitude?: number | null;
  message?: string | null;
  phone: string;
  smsConsent?: boolean;
  state: string;
  zipcode: string;
}
