/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterDto {
  email: string;
  lastName?: string;
  name: string;
  password: string;
  termsAndConditions: true;
}
