/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RoleResponseDto {
  createdAt: string;
  deletedAt: string | null;
  description: string | null;
  id: string;
  isSystem: boolean;
  name: string;
  permissions?: Array<{
'id': string;
'name': string;
'description': string | null;
'module': string;
'subject': string;
'action': string;
'createdAt': string;
'updatedAt': string;
'deletedAt': string | null;
'conditions': ({
[key: string]: any;
}) | null;
'fields': Array<string>;
}>;
  updatedAt: string;
}
