/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SocialMediaTopicResponse {
  description: string;
  id: string;
  tags: Array<string>;
  title: string;
  trendScore: number;
  whyViral: string;
}
