/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdatePostDto {

  /**
   * Industry/vertical used to guide the AI writer (tone, examples, E-E-A-T grounding). Only used when generateWithAi=true. Example: "Desarrollo Web", "Fintech", "Salud". Defaults to "industry insights" if omitted.
   */
  aiNiche?: string;

  /**
   * Target word count for the AI-generated article body (300-5000). Only used when generateWithAi=true. Defaults to 1200 if omitted.
   */
  aiWordCount?: number;
  categoryId?: string | null;

  /**
   * When true, the backend will automatically generate the full post content (Markdown), SEO fields, and optionally a hero image using Google Gemini + Tavily research (E-E-A-T). Generation + image upload to R2 happens BEFORE the database transaction. Client-provided values for content/SEO/image take precedence and override generated ones. Requires valid TAVILY_API_KEY and GEMINI_API_KEY.
   */
  generateWithAi?: boolean;

  /**
   * SEO meta description. HTML is stripped server-side.
   */
  metaDescription?: string | null;

  /**
   * Comma-separated keywords. HTML is stripped server-side.
   */
  metaKeywords?: string | null;

  /**
   * SEO meta title. HTML is stripped server-side.
   */
  metaTitle?: string | null;

  /**
   * Main article body. Accepts Markdown (recommended) or safe HTML. Server will sanitize on every create/update using a strict OWASP allowlist that supports: headings, paragraphs, lists, bold/italic/underline/strike, links, blockquotes, code/pre, images, and basic tables. Dangerous tags/attributes/scripts are always stripped. Client-provided values override AI-generated ones.
   */
  postContent?: string;
  postCoverImage?: string | null;

  /**
   * Short excerpt / description. HTML is stripped server-side.
   */
  postExcerpt?: string | null;
  postStatus?: 'draft' | 'published' | 'scheduled';

  /**
   * Post title. HTML is stripped server-side (plain text only).
   */
  postTitle?: string;

  /**
   * URL slug. If omitted, generated from title. HTML is stripped server-side.
   */
  postTitleSlug?: string;
  scheduledAt?: string | null;
}
