/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserDto {
  email?: string;
  lastName?: string;
  name?: string;
  permissionIds?: Array<string>;
  phone?: string;
  roleIds?: Array<string>;
}
