/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateRoleDto {
  description?: string | null;
  name?: string;
  permissions?: Array<{
'permissionId': string;
'conditions'?: ({
[key: string]: any;
}) | null;
'fields'?: Array<string>;
}>;
}
