/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserPermissionResponseDto {
  assignedAt: string;
  assignedBy: string | null;
  conditions: ({
[key: string]: any;
}) | null;
  fields: Array<string>;
  isGranted: boolean;
  permission: {
'id': string;
'name': string;
'description': string | null;
'module': string;
'subject': string;
'action': string;
'createdAt': string;
'updatedAt': string;
'deletedAt': string | null;
};
  permissionId: string;
  userId: string;
}
