/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserListResponse {
  data: Array<{
'id': string;
'name': string;
'lastName': string | null;
'email': string;
'phone': string | null;
'emailVerifiedAt': string | null;
'passwordConfirmedAt': string | null;
'createdAt': string;
'updatedAt': string;
'deletedAt': string | null;
'roles': Array<{
'id': string;
'name': string;
'description': string | null;
}>;
'permissions': Array<{
'action': string;
'subject': string;
}>;
}>;
  limit: number;
  page: number;
  total: number;
}
