/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserListResponse {
  data: Array<{
'id': string;
'name': string;
'lastName': string | null;
'username': string | null;
'email': string;
'phone': string | null;
'emailVerifiedAt': string | null;
'passwordConfirmedAt': string | null;
'createdAt': string;
'updatedAt': string;
'deletedAt': string | null;
'roles': Array<{
'id': string;
'name': string;
'description': string | null;
}>;
'permissions': Array<{
'action': string;
'subject': string;
}>;
'dateOfBirth': string | null;
'address': string | null;
'address2': string | null;
'zipCode': string | null;
'city': string | null;
'state': string | null;
'country': string | null;
'gender': string | null;
'profilePhotoUrl': string | null;
'totpEnabled': boolean;
'mustChangePassword': boolean;
}>;
  limit: number;
  page: number;
  total: number;
}
