/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  address: string | null;
  address2: string | null;
  city: string | null;
  country: string | null;
  createdAt: string;
  dateOfBirth: string | null;
  deletedAt: string | null;
  email: string;
  emailVerifiedAt: string | null;
  gender: string | null;
  id: string;
  lastName: string | null;
  mustChangePassword: boolean;
  name: string;
  passwordConfirmedAt: string | null;
  permissions: Array<{
'action': string;
'subject': string;
}>;
  phone: string | null;
  profilePhotoUrl: string | null;
  roles: Array<{
'id': string;
'name': string;
'description': string | null;
}>;
  state: string | null;
  totpEnabled: boolean;
  updatedAt: string;
  username: string | null;
  zipCode: string | null;
}
