/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { activityLogControllerFindAll } from '../fn/activity-logs/activity-log-controller-find-all';
import { ActivityLogControllerFindAll$Params } from '../fn/activity-logs/activity-log-controller-find-all';
import { activityLogControllerFindOne } from '../fn/activity-logs/activity-log-controller-find-one';
import { ActivityLogControllerFindOne$Params } from '../fn/activity-logs/activity-log-controller-find-one';
import { activityLogControllerRemove } from '../fn/activity-logs/activity-log-controller-remove';
import { ActivityLogControllerRemove$Params } from '../fn/activity-logs/activity-log-controller-remove';
import { ActivityLogResponse } from '../models/activity-log-response';

@Injectable({ providedIn: 'root' })
export class ActivityLogsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `activityLogControllerFindAll()` */
  static readonly ActivityLogControllerFindAllPath = '/api/v1/activity-logs';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `activityLogControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  activityLogControllerFindAll$Response(params?: ActivityLogControllerFindAll$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<ActivityLogResponse>>> {
    const obs = activityLogControllerFindAll(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `activityLogControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  activityLogControllerFindAll(params?: ActivityLogControllerFindAll$Params, context?: HttpContext): Promise<Array<ActivityLogResponse>> {
    const resp = this.activityLogControllerFindAll$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<ActivityLogResponse>>): Array<ActivityLogResponse> => r.body);
  }

  /** Path part for operation `activityLogControllerFindOne()` */
  static readonly ActivityLogControllerFindOnePath = '/api/v1/activity-logs/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `activityLogControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  activityLogControllerFindOne$Response(params: ActivityLogControllerFindOne$Params, context?: HttpContext): Promise<StrictHttpResponse<ActivityLogResponse>> {
    const obs = activityLogControllerFindOne(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `activityLogControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  activityLogControllerFindOne(params: ActivityLogControllerFindOne$Params, context?: HttpContext): Promise<ActivityLogResponse> {
    const resp = this.activityLogControllerFindOne$Response(params, context);
    return resp.then((r: StrictHttpResponse<ActivityLogResponse>): ActivityLogResponse => r.body);
  }

  /** Path part for operation `activityLogControllerRemove()` */
  static readonly ActivityLogControllerRemovePath = '/api/v1/activity-logs/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `activityLogControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  activityLogControllerRemove$Response(params: ActivityLogControllerRemove$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = activityLogControllerRemove(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `activityLogControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  activityLogControllerRemove(params: ActivityLogControllerRemove$Params, context?: HttpContext): Promise<void> {
    const resp = this.activityLogControllerRemove$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
