/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { appControllerRedirectToDocs } from '../fn/app/app-controller-redirect-to-docs';
import { AppControllerRedirectToDocs$Params } from '../fn/app/app-controller-redirect-to-docs';

@Injectable({ providedIn: 'root' })
export class AppService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `appControllerRedirectToDocs()` */
  static readonly AppControllerRedirectToDocsPath = '/api/v1';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appControllerRedirectToDocs()` instead.
   *
   * This method doesn't expect any request body.
   */
  appControllerRedirectToDocs$Response(params?: AppControllerRedirectToDocs$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = appControllerRedirectToDocs(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appControllerRedirectToDocs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appControllerRedirectToDocs(params?: AppControllerRedirectToDocs$Params, context?: HttpContext): Promise<void> {
    const resp = this.appControllerRedirectToDocs$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
