/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AppointmentListResponse } from '../models/appointment-list-response';
import { AppointmentResponse } from '../models/appointment-response';
import { appointmentsControllerBulkDelete } from '../fn/appointments/appointments-controller-bulk-delete';
import { AppointmentsControllerBulkDelete$Params } from '../fn/appointments/appointments-controller-bulk-delete';
import { appointmentsControllerBulkRestore } from '../fn/appointments/appointments-controller-bulk-restore';
import { AppointmentsControllerBulkRestore$Params } from '../fn/appointments/appointments-controller-bulk-restore';
import { appointmentsControllerCreate } from '../fn/appointments/appointments-controller-create';
import { AppointmentsControllerCreate$Params } from '../fn/appointments/appointments-controller-create';
import { appointmentsControllerDelete } from '../fn/appointments/appointments-controller-delete';
import { AppointmentsControllerDelete$Params } from '../fn/appointments/appointments-controller-delete';
import { appointmentsControllerExport$Csv } from '../fn/appointments/appointments-controller-export-csv';
import { AppointmentsControllerExport$Csv$Params } from '../fn/appointments/appointments-controller-export-csv';
import { appointmentsControllerExport$Pdf } from '../fn/appointments/appointments-controller-export-pdf';
import { AppointmentsControllerExport$Pdf$Params } from '../fn/appointments/appointments-controller-export-pdf';
import { appointmentsControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet } from '../fn/appointments/appointments-controller-export-vnd-openxmlformats-officedocument-spreadsheetml-sheet';
import { AppointmentsControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Params } from '../fn/appointments/appointments-controller-export-vnd-openxmlformats-officedocument-spreadsheetml-sheet';
import { appointmentsControllerFindAll } from '../fn/appointments/appointments-controller-find-all';
import { AppointmentsControllerFindAll$Params } from '../fn/appointments/appointments-controller-find-all';
import { appointmentsControllerFindOne } from '../fn/appointments/appointments-controller-find-one';
import { AppointmentsControllerFindOne$Params } from '../fn/appointments/appointments-controller-find-one';
import { appointmentsControllerMarkRead } from '../fn/appointments/appointments-controller-mark-read';
import { AppointmentsControllerMarkRead$Params } from '../fn/appointments/appointments-controller-mark-read';
import { appointmentsControllerRestore } from '../fn/appointments/appointments-controller-restore';
import { AppointmentsControllerRestore$Params } from '../fn/appointments/appointments-controller-restore';
import { appointmentsControllerUpdate } from '../fn/appointments/appointments-controller-update';
import { AppointmentsControllerUpdate$Params } from '../fn/appointments/appointments-controller-update';
import { CreateAppointmentResponse } from '../models/create-appointment-response';

@Injectable({ providedIn: 'root' })
export class AppointmentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `appointmentsControllerFindAll()` */
  static readonly AppointmentsControllerFindAllPath = '/api/v1/appointments';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appointmentsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  appointmentsControllerFindAll$Response(params?: AppointmentsControllerFindAll$Params, context?: HttpContext): Promise<StrictHttpResponse<AppointmentListResponse>> {
    const obs = appointmentsControllerFindAll(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appointmentsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appointmentsControllerFindAll(params?: AppointmentsControllerFindAll$Params, context?: HttpContext): Promise<AppointmentListResponse> {
    const resp = this.appointmentsControllerFindAll$Response(params, context);
    return resp.then((r: StrictHttpResponse<AppointmentListResponse>): AppointmentListResponse => r.body);
  }

  /** Path part for operation `appointmentsControllerCreate()` */
  static readonly AppointmentsControllerCreatePath = '/api/v1/appointments';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appointmentsControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  appointmentsControllerCreate$Response(params: AppointmentsControllerCreate$Params, context?: HttpContext): Promise<StrictHttpResponse<CreateAppointmentResponse>> {
    const obs = appointmentsControllerCreate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appointmentsControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  appointmentsControllerCreate(params: AppointmentsControllerCreate$Params, context?: HttpContext): Promise<CreateAppointmentResponse> {
    const resp = this.appointmentsControllerCreate$Response(params, context);
    return resp.then((r: StrictHttpResponse<CreateAppointmentResponse>): CreateAppointmentResponse => r.body);
  }

  /** Path part for operation `appointmentsControllerExport()` */
  static readonly AppointmentsControllerExportPath = '/api/v1/appointments/export';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appointmentsControllerExport$Csv()` instead.
   *
   * This method doesn't expect any request body.
   */
  appointmentsControllerExport$Csv$Response(params?: AppointmentsControllerExport$Csv$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = appointmentsControllerExport$Csv(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appointmentsControllerExport$Csv$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appointmentsControllerExport$Csv(params?: AppointmentsControllerExport$Csv$Params, context?: HttpContext): Promise<any> {
    const resp = this.appointmentsControllerExport$Csv$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appointmentsControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet()` instead.
   *
   * This method doesn't expect any request body.
   */
  appointmentsControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Response(params?: AppointmentsControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = appointmentsControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appointmentsControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appointmentsControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet(params?: AppointmentsControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Params, context?: HttpContext): Promise<any> {
    const resp = this.appointmentsControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appointmentsControllerExport$Pdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  appointmentsControllerExport$Pdf$Response(params?: AppointmentsControllerExport$Pdf$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = appointmentsControllerExport$Pdf(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appointmentsControllerExport$Pdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appointmentsControllerExport$Pdf(params?: AppointmentsControllerExport$Pdf$Params, context?: HttpContext): Promise<any> {
    const resp = this.appointmentsControllerExport$Pdf$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `appointmentsControllerFindOne()` */
  static readonly AppointmentsControllerFindOnePath = '/api/v1/appointments/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appointmentsControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  appointmentsControllerFindOne$Response(params: AppointmentsControllerFindOne$Params, context?: HttpContext): Promise<StrictHttpResponse<AppointmentResponse>> {
    const obs = appointmentsControllerFindOne(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appointmentsControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appointmentsControllerFindOne(params: AppointmentsControllerFindOne$Params, context?: HttpContext): Promise<AppointmentResponse> {
    const resp = this.appointmentsControllerFindOne$Response(params, context);
    return resp.then((r: StrictHttpResponse<AppointmentResponse>): AppointmentResponse => r.body);
  }

  /** Path part for operation `appointmentsControllerDelete()` */
  static readonly AppointmentsControllerDeletePath = '/api/v1/appointments/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appointmentsControllerDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  appointmentsControllerDelete$Response(params: AppointmentsControllerDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = appointmentsControllerDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appointmentsControllerDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appointmentsControllerDelete(params: AppointmentsControllerDelete$Params, context?: HttpContext): Promise<void> {
    const resp = this.appointmentsControllerDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `appointmentsControllerUpdate()` */
  static readonly AppointmentsControllerUpdatePath = '/api/v1/appointments/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appointmentsControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  appointmentsControllerUpdate$Response(params: AppointmentsControllerUpdate$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = appointmentsControllerUpdate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appointmentsControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  appointmentsControllerUpdate(params: AppointmentsControllerUpdate$Params, context?: HttpContext): Promise<void> {
    const resp = this.appointmentsControllerUpdate$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `appointmentsControllerMarkRead()` */
  static readonly AppointmentsControllerMarkReadPath = '/api/v1/appointments/{id}/read';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appointmentsControllerMarkRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  appointmentsControllerMarkRead$Response(params: AppointmentsControllerMarkRead$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = appointmentsControllerMarkRead(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appointmentsControllerMarkRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appointmentsControllerMarkRead(params: AppointmentsControllerMarkRead$Params, context?: HttpContext): Promise<any> {
    const resp = this.appointmentsControllerMarkRead$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `appointmentsControllerRestore()` */
  static readonly AppointmentsControllerRestorePath = '/api/v1/appointments/{id}/restore';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appointmentsControllerRestore()` instead.
   *
   * This method doesn't expect any request body.
   */
  appointmentsControllerRestore$Response(params: AppointmentsControllerRestore$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = appointmentsControllerRestore(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appointmentsControllerRestore$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appointmentsControllerRestore(params: AppointmentsControllerRestore$Params, context?: HttpContext): Promise<any> {
    const resp = this.appointmentsControllerRestore$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `appointmentsControllerBulkDelete()` */
  static readonly AppointmentsControllerBulkDeletePath = '/api/v1/appointments/bulk-delete';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appointmentsControllerBulkDelete()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  appointmentsControllerBulkDelete$Response(params: AppointmentsControllerBulkDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = appointmentsControllerBulkDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appointmentsControllerBulkDelete$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  appointmentsControllerBulkDelete(params: AppointmentsControllerBulkDelete$Params, context?: HttpContext): Promise<any> {
    const resp = this.appointmentsControllerBulkDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `appointmentsControllerBulkRestore()` */
  static readonly AppointmentsControllerBulkRestorePath = '/api/v1/appointments/bulk-restore';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appointmentsControllerBulkRestore()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  appointmentsControllerBulkRestore$Response(params: AppointmentsControllerBulkRestore$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = appointmentsControllerBulkRestore(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appointmentsControllerBulkRestore$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  appointmentsControllerBulkRestore(params: AppointmentsControllerBulkRestore$Params, context?: HttpContext): Promise<any> {
    const resp = this.appointmentsControllerBulkRestore$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

}
