/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';
import { UserResponse } from '../models/user-response';

import { authControllerChangePassword } from '../fn/auth/auth-controller-change-password';
import { AuthControllerChangePassword$Params } from '../fn/auth/auth-controller-change-password';
import { authControllerForgotPassword } from '../fn/auth/auth-controller-forgot-password';
import { AuthControllerForgotPassword$Params } from '../fn/auth/auth-controller-forgot-password';
import { authControllerLogin } from '../fn/auth/auth-controller-login';
import { AuthControllerLogin$Params } from '../fn/auth/auth-controller-login';
import { authControllerLogout } from '../fn/auth/auth-controller-logout';
import { AuthControllerLogout$Params } from '../fn/auth/auth-controller-logout';
import { authControllerLogoutAll } from '../fn/auth/auth-controller-logout-all';
import { AuthControllerLogoutAll$Params } from '../fn/auth/auth-controller-logout-all';
import { authControllerMe } from '../fn/auth/auth-controller-me';
import { AuthControllerMe$Params } from '../fn/auth/auth-controller-me';
import { authControllerRefresh } from '../fn/auth/auth-controller-refresh';
import { AuthControllerRefresh$Params } from '../fn/auth/auth-controller-refresh';
import { authControllerRegister } from '../fn/auth/auth-controller-register';
import { AuthControllerRegister$Params } from '../fn/auth/auth-controller-register';
import { authControllerResendVerificationCode } from '../fn/auth/auth-controller-resend-verification-code';
import { AuthControllerResendVerificationCode$Params } from '../fn/auth/auth-controller-resend-verification-code';
import { authControllerResetPassword } from '../fn/auth/auth-controller-reset-password';
import { AuthControllerResetPassword$Params } from '../fn/auth/auth-controller-reset-password';
import { authControllerUpdateMe } from '../fn/auth/auth-controller-update-me';
import { AuthControllerUpdateMe$Params } from '../fn/auth/auth-controller-update-me';
import { authControllerUploadPhoto } from '../fn/auth/auth-controller-upload-photo';
import { AuthControllerUploadPhoto$Params } from '../fn/auth/auth-controller-upload-photo';
import { authControllerVerifyEmail } from '../fn/auth/auth-controller-verify-email';
import { AuthControllerVerifyEmail$Params } from '../fn/auth/auth-controller-verify-email';
import { authControllerVerifyTwoFactor } from '../fn/auth/auth-controller-verify-two-factor';
import { AuthControllerVerifyTwoFactor$Params } from '../fn/auth/auth-controller-verify-two-factor';

@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `authControllerRegister()` */
  static readonly AuthControllerRegisterPath = '/api/v1/auth/register';

  /**
   * Register a new user — sends a 6-digit verification code by email.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerRegister()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerRegister$Response(params: AuthControllerRegister$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = authControllerRegister(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Register a new user — sends a 6-digit verification code by email.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerRegister$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerRegister(params: AuthControllerRegister$Params, context?: HttpContext): Promise<void> {
    const resp = this.authControllerRegister$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `authControllerVerifyEmail()` */
  static readonly AuthControllerVerifyEmailPath = '/api/v1/auth/verify-email';

  /**
   * Verify a registration email with the 6-digit OTP.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerVerifyEmail()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerVerifyEmail$Response(params: AuthControllerVerifyEmail$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = authControllerVerifyEmail(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Verify a registration email with the 6-digit OTP.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerVerifyEmail$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerVerifyEmail(params: AuthControllerVerifyEmail$Params, context?: HttpContext): Promise<void> {
    const resp = this.authControllerVerifyEmail$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `authControllerResendVerificationCode()` */
  static readonly AuthControllerResendVerificationCodePath = '/api/v1/auth/resend-verification-code';

  /**
   * Resend the email-verification code (60 s throttle per email).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerResendVerificationCode()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerResendVerificationCode$Response(params: AuthControllerResendVerificationCode$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = authControllerResendVerificationCode(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Resend the email-verification code (60 s throttle per email).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerResendVerificationCode$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerResendVerificationCode(params: AuthControllerResendVerificationCode$Params, context?: HttpContext): Promise<void> {
    const resp = this.authControllerResendVerificationCode$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `authControllerLogin()` */
  static readonly AuthControllerLoginPath = '/api/v1/auth/login';

  /**
   * Password login (returns tokens, or a 2FA challenge if enabled).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerLogin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerLogin$Response(params: AuthControllerLogin$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = authControllerLogin(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Password login (returns tokens, or a 2FA challenge if enabled).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerLogin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerLogin(params: AuthControllerLogin$Params, context?: HttpContext): Promise<void> {
    const resp = this.authControllerLogin$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `authControllerVerifyTwoFactor()` */
  static readonly AuthControllerVerifyTwoFactorPath = '/api/v1/auth/two-factor/verify';

  /**
   * Complete the 2FA challenge with a TOTP or backup code.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerVerifyTwoFactor()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerVerifyTwoFactor$Response(params: AuthControllerVerifyTwoFactor$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = authControllerVerifyTwoFactor(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Complete the 2FA challenge with a TOTP or backup code.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerVerifyTwoFactor$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerVerifyTwoFactor(params: AuthControllerVerifyTwoFactor$Params, context?: HttpContext): Promise<void> {
    const resp = this.authControllerVerifyTwoFactor$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `authControllerRefresh()` */
  static readonly AuthControllerRefreshPath = '/api/v1/auth/refresh';

  /**
   * Rotate the refresh token + emit a fresh access token.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerRefresh()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerRefresh$Response(params: AuthControllerRefresh$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = authControllerRefresh(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Rotate the refresh token + emit a fresh access token.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerRefresh$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerRefresh(params: AuthControllerRefresh$Params, context?: HttpContext): Promise<void> {
    const resp = this.authControllerRefresh$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `authControllerForgotPassword()` */
  static readonly AuthControllerForgotPasswordPath = '/api/v1/auth/forgot-password';

  /**
   * Send a 6-digit password-reset code (silent no-op on unknown email).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerForgotPassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerForgotPassword$Response(params: AuthControllerForgotPassword$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = authControllerForgotPassword(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Send a 6-digit password-reset code (silent no-op on unknown email).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerForgotPassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerForgotPassword(params: AuthControllerForgotPassword$Params, context?: HttpContext): Promise<void> {
    const resp = this.authControllerForgotPassword$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `authControllerResetPassword()` */
  static readonly AuthControllerResetPasswordPath = '/api/v1/auth/reset-password';

  /**
   * Consume reset code + set new password; revokes ALL sessions.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerResetPassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerResetPassword$Response(params: AuthControllerResetPassword$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = authControllerResetPassword(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Consume reset code + set new password; revokes ALL sessions.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerResetPassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerResetPassword(params: AuthControllerResetPassword$Params, context?: HttpContext): Promise<void> {
    const resp = this.authControllerResetPassword$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `authControllerChangePassword()` */
  static readonly AuthControllerChangePasswordPath = '/api/v1/auth/change-password';

  /**
   * Authenticated user changes their own password; keeps current session.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerChangePassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerChangePassword$Response(params: AuthControllerChangePassword$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = authControllerChangePassword(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Authenticated user changes their own password; keeps current session.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerChangePassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerChangePassword(params: AuthControllerChangePassword$Params, context?: HttpContext): Promise<void> {
    const resp = this.authControllerChangePassword$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `authControllerLogout()` */
  static readonly AuthControllerLogoutPath = '/api/v1/auth/logout';

  /**
   * Revoke the calling session.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerLogout()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerLogout$Response(params?: AuthControllerLogout$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = authControllerLogout(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Revoke the calling session.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerLogout$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerLogout(params?: AuthControllerLogout$Params, context?: HttpContext): Promise<void> {
    const resp = this.authControllerLogout$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `authControllerLogoutAll()` */
  static readonly AuthControllerLogoutAllPath = '/api/v1/auth/logout-all';

  /**
   * Revoke every other session (keep the current one).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerLogoutAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerLogoutAll$Response(params?: AuthControllerLogoutAll$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = authControllerLogoutAll(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Revoke every other session (keep the current one).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerLogoutAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerLogoutAll(params?: AuthControllerLogoutAll$Params, context?: HttpContext): Promise<void> {
    const resp = this.authControllerLogoutAll$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `authControllerMe()` */
  static readonly AuthControllerMePath = '/api/v1/auth/me';

  /**
   * Current user identity, profile, roles + effective permissions.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerMe()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerMe$Response(params?: AuthControllerMe$Params, context?: HttpContext): Promise<StrictHttpResponse<UserResponse>> {
    const obs = authControllerMe(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Current user identity, profile, roles + effective permissions.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerMe$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerMe(params?: AuthControllerMe$Params, context?: HttpContext): Promise<UserResponse> {
    const resp = this.authControllerMe$Response(params, context);
    return resp.then((r: StrictHttpResponse<UserResponse>): UserResponse => r.body);
  }

  /** Path part for operation `authControllerUpdateMe()` */
  static readonly AuthControllerUpdateMePath = '/api/v1/auth/me';

  /**
   * Update own profile (whitelist of non-auth columns).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerUpdateMe()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerUpdateMe$Response(params: AuthControllerUpdateMe$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = authControllerUpdateMe(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Update own profile (whitelist of non-auth columns).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerUpdateMe$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authControllerUpdateMe(params: AuthControllerUpdateMe$Params, context?: HttpContext): Promise<void> {
    const resp = this.authControllerUpdateMe$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `authControllerUploadPhoto()` */
  static readonly AuthControllerUploadPhotoPath = '/api/v1/auth/me/profile-photo';

  /**
   * Upload / replace own profile photo (R2 via circuit breaker).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authControllerUploadPhoto()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerUploadPhoto$Response(params?: AuthControllerUploadPhoto$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = authControllerUploadPhoto(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Upload / replace own profile photo (R2 via circuit breaker).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authControllerUploadPhoto$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  authControllerUploadPhoto(params?: AuthControllerUploadPhoto$Params, context?: HttpContext): Promise<void> {
    const resp = this.authControllerUploadPhoto$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
