/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { sessionsControllerListSessions } from '../fn/auth-sessions/sessions-controller-list-sessions';
import { SessionsControllerListSessions$Params } from '../fn/auth-sessions/sessions-controller-list-sessions';
import { sessionsControllerListTrustedDevices } from '../fn/auth-sessions/sessions-controller-list-trusted-devices';
import { SessionsControllerListTrustedDevices$Params } from '../fn/auth-sessions/sessions-controller-list-trusted-devices';
import { sessionsControllerRevokeAllTrustedDevices } from '../fn/auth-sessions/sessions-controller-revoke-all-trusted-devices';
import { SessionsControllerRevokeAllTrustedDevices$Params } from '../fn/auth-sessions/sessions-controller-revoke-all-trusted-devices';
import { sessionsControllerRevokeSession } from '../fn/auth-sessions/sessions-controller-revoke-session';
import { SessionsControllerRevokeSession$Params } from '../fn/auth-sessions/sessions-controller-revoke-session';
import { sessionsControllerRevokeTrustedDevice } from '../fn/auth-sessions/sessions-controller-revoke-trusted-device';
import { SessionsControllerRevokeTrustedDevice$Params } from '../fn/auth-sessions/sessions-controller-revoke-trusted-device';

@Injectable({ providedIn: 'root' })
export class AuthSessionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `sessionsControllerListSessions()` */
  static readonly SessionsControllerListSessionsPath = '/api/v1/auth/sessions';

  /**
   * List active sessions for the caller.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sessionsControllerListSessions()` instead.
   *
   * This method doesn't expect any request body.
   */
  sessionsControllerListSessions$Response(params?: SessionsControllerListSessions$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = sessionsControllerListSessions(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List active sessions for the caller.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sessionsControllerListSessions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sessionsControllerListSessions(params?: SessionsControllerListSessions$Params, context?: HttpContext): Promise<void> {
    const resp = this.sessionsControllerListSessions$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `sessionsControllerRevokeSession()` */
  static readonly SessionsControllerRevokeSessionPath = '/api/v1/auth/sessions/{id}';

  /**
   * Revoke one of own sessions by id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sessionsControllerRevokeSession()` instead.
   *
   * This method doesn't expect any request body.
   */
  sessionsControllerRevokeSession$Response(params: SessionsControllerRevokeSession$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = sessionsControllerRevokeSession(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Revoke one of own sessions by id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sessionsControllerRevokeSession$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sessionsControllerRevokeSession(params: SessionsControllerRevokeSession$Params, context?: HttpContext): Promise<void> {
    const resp = this.sessionsControllerRevokeSession$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `sessionsControllerListTrustedDevices()` */
  static readonly SessionsControllerListTrustedDevicesPath = '/api/v1/auth/trusted-devices';

  /**
   * List trusted devices (30-day cookies) for the caller.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sessionsControllerListTrustedDevices()` instead.
   *
   * This method doesn't expect any request body.
   */
  sessionsControllerListTrustedDevices$Response(params?: SessionsControllerListTrustedDevices$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = sessionsControllerListTrustedDevices(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List trusted devices (30-day cookies) for the caller.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sessionsControllerListTrustedDevices$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sessionsControllerListTrustedDevices(params?: SessionsControllerListTrustedDevices$Params, context?: HttpContext): Promise<void> {
    const resp = this.sessionsControllerListTrustedDevices$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `sessionsControllerRevokeAllTrustedDevices()` */
  static readonly SessionsControllerRevokeAllTrustedDevicesPath = '/api/v1/auth/trusted-devices';

  /**
   * Revoke ALL trusted devices.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sessionsControllerRevokeAllTrustedDevices()` instead.
   *
   * This method doesn't expect any request body.
   */
  sessionsControllerRevokeAllTrustedDevices$Response(params?: SessionsControllerRevokeAllTrustedDevices$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = sessionsControllerRevokeAllTrustedDevices(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Revoke ALL trusted devices.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sessionsControllerRevokeAllTrustedDevices$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sessionsControllerRevokeAllTrustedDevices(params?: SessionsControllerRevokeAllTrustedDevices$Params, context?: HttpContext): Promise<void> {
    const resp = this.sessionsControllerRevokeAllTrustedDevices$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `sessionsControllerRevokeTrustedDevice()` */
  static readonly SessionsControllerRevokeTrustedDevicePath = '/api/v1/auth/trusted-devices/{id}';

  /**
   * Revoke a single trusted device.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sessionsControllerRevokeTrustedDevice()` instead.
   *
   * This method doesn't expect any request body.
   */
  sessionsControllerRevokeTrustedDevice$Response(params: SessionsControllerRevokeTrustedDevice$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = sessionsControllerRevokeTrustedDevice(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Revoke a single trusted device.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sessionsControllerRevokeTrustedDevice$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sessionsControllerRevokeTrustedDevice(params: SessionsControllerRevokeTrustedDevice$Params, context?: HttpContext): Promise<void> {
    const resp = this.sessionsControllerRevokeTrustedDevice$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
