/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { twoFactorControllerDisable } from '../fn/auth-2-fa/two-factor-controller-disable';
import { TwoFactorControllerDisable$Params } from '../fn/auth-2-fa/two-factor-controller-disable';
import { twoFactorControllerEnable } from '../fn/auth-2-fa/two-factor-controller-enable';
import { TwoFactorControllerEnable$Params } from '../fn/auth-2-fa/two-factor-controller-enable';
import { twoFactorControllerRegenerate } from '../fn/auth-2-fa/two-factor-controller-regenerate';
import { TwoFactorControllerRegenerate$Params } from '../fn/auth-2-fa/two-factor-controller-regenerate';
import { twoFactorControllerSetup } from '../fn/auth-2-fa/two-factor-controller-setup';
import { TwoFactorControllerSetup$Params } from '../fn/auth-2-fa/two-factor-controller-setup';

@Injectable({ providedIn: 'root' })
export class Auth2FaService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `twoFactorControllerSetup()` */
  static readonly TwoFactorControllerSetupPath = '/api/v1/auth/two-factor/setup';

  /**
   * Start TOTP setup — returns the secret + QR code.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `twoFactorControllerSetup()` instead.
   *
   * This method doesn't expect any request body.
   */
  twoFactorControllerSetup$Response(params?: TwoFactorControllerSetup$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = twoFactorControllerSetup(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Start TOTP setup — returns the secret + QR code.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `twoFactorControllerSetup$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  twoFactorControllerSetup(params?: TwoFactorControllerSetup$Params, context?: HttpContext): Promise<void> {
    const resp = this.twoFactorControllerSetup$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `twoFactorControllerEnable()` */
  static readonly TwoFactorControllerEnablePath = '/api/v1/auth/two-factor/enable';

  /**
   * Confirm setup with a TOTP code and receive backup codes.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `twoFactorControllerEnable()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  twoFactorControllerEnable$Response(params: TwoFactorControllerEnable$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = twoFactorControllerEnable(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Confirm setup with a TOTP code and receive backup codes.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `twoFactorControllerEnable$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  twoFactorControllerEnable(params: TwoFactorControllerEnable$Params, context?: HttpContext): Promise<void> {
    const resp = this.twoFactorControllerEnable$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `twoFactorControllerDisable()` */
  static readonly TwoFactorControllerDisablePath = '/api/v1/auth/two-factor/disable';

  /**
   * Disable TOTP and wipe backup codes + trusted devices.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `twoFactorControllerDisable()` instead.
   *
   * This method doesn't expect any request body.
   */
  twoFactorControllerDisable$Response(params?: TwoFactorControllerDisable$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = twoFactorControllerDisable(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Disable TOTP and wipe backup codes + trusted devices.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `twoFactorControllerDisable$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  twoFactorControllerDisable(params?: TwoFactorControllerDisable$Params, context?: HttpContext): Promise<void> {
    const resp = this.twoFactorControllerDisable$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `twoFactorControllerRegenerate()` */
  static readonly TwoFactorControllerRegeneratePath = '/api/v1/auth/two-factor/backup-codes/regenerate';

  /**
   * Regenerate 8 new backup codes (shown once).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `twoFactorControllerRegenerate()` instead.
   *
   * This method doesn't expect any request body.
   */
  twoFactorControllerRegenerate$Response(params?: TwoFactorControllerRegenerate$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = twoFactorControllerRegenerate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Regenerate 8 new backup codes (shown once).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `twoFactorControllerRegenerate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  twoFactorControllerRegenerate(params?: TwoFactorControllerRegenerate$Params, context?: HttpContext): Promise<void> {
    const resp = this.twoFactorControllerRegenerate$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
