/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { socialAuthControllerCallback } from '../fn/auth-social/social-auth-controller-callback';
import { SocialAuthControllerCallback$Params } from '../fn/auth-social/social-auth-controller-callback';
import { socialAuthControllerRedirect } from '../fn/auth-social/social-auth-controller-redirect';
import { SocialAuthControllerRedirect$Params } from '../fn/auth-social/social-auth-controller-redirect';
import { socialAuthControllerUnlink } from '../fn/auth-social/social-auth-controller-unlink';
import { SocialAuthControllerUnlink$Params } from '../fn/auth-social/social-auth-controller-unlink';

@Injectable({ providedIn: 'root' })
export class AuthSocialService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `socialAuthControllerRedirect()` */
  static readonly SocialAuthControllerRedirectPath = '/api/v1/auth/google/redirect';

  /**
   * Begin Google sign-in (sets the CSRF state cookie).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `socialAuthControllerRedirect()` instead.
   *
   * This method doesn't expect any request body.
   */
  socialAuthControllerRedirect$Response(params?: SocialAuthControllerRedirect$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = socialAuthControllerRedirect(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Begin Google sign-in (sets the CSRF state cookie).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `socialAuthControllerRedirect$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  socialAuthControllerRedirect(params?: SocialAuthControllerRedirect$Params, context?: HttpContext): Promise<void> {
    const resp = this.socialAuthControllerRedirect$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `socialAuthControllerCallback()` */
  static readonly SocialAuthControllerCallbackPath = '/api/v1/auth/google/callback';

  /**
   * Complete Google sign-in (verifies state + exchanges code).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `socialAuthControllerCallback()` instead.
   *
   * This method doesn't expect any request body.
   */
  socialAuthControllerCallback$Response(params?: SocialAuthControllerCallback$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = socialAuthControllerCallback(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Complete Google sign-in (verifies state + exchanges code).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `socialAuthControllerCallback$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  socialAuthControllerCallback(params?: SocialAuthControllerCallback$Params, context?: HttpContext): Promise<void> {
    const resp = this.socialAuthControllerCallback$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `socialAuthControllerUnlink()` */
  static readonly SocialAuthControllerUnlinkPath = '/api/v1/auth/google';

  /**
   * Unlink Google account (requires fresh password).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `socialAuthControllerUnlink()` instead.
   *
   * This method doesn't expect any request body.
   */
  socialAuthControllerUnlink$Response(params?: SocialAuthControllerUnlink$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = socialAuthControllerUnlink(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Unlink Google account (requires fresh password).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `socialAuthControllerUnlink$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  socialAuthControllerUnlink(params?: SocialAuthControllerUnlink$Params, context?: HttpContext): Promise<void> {
    const resp = this.socialAuthControllerUnlink$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
