/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { backupControllerDownload } from '../fn/backups/backup-controller-download';
import { BackupControllerDownload$Params } from '../fn/backups/backup-controller-download';
import { backupControllerExport$Csv } from '../fn/backups/backup-controller-export-csv';
import { BackupControllerExport$Csv$Params } from '../fn/backups/backup-controller-export-csv';
import { backupControllerExport$Pdf } from '../fn/backups/backup-controller-export-pdf';
import { BackupControllerExport$Pdf$Params } from '../fn/backups/backup-controller-export-pdf';
import { backupControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet } from '../fn/backups/backup-controller-export-vnd-openxmlformats-officedocument-spreadsheetml-sheet';
import { BackupControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Params } from '../fn/backups/backup-controller-export-vnd-openxmlformats-officedocument-spreadsheetml-sheet';
import { backupControllerFindAll } from '../fn/backups/backup-controller-find-all';
import { BackupControllerFindAll$Params } from '../fn/backups/backup-controller-find-all';
import { backupControllerFindOne } from '../fn/backups/backup-controller-find-one';
import { BackupControllerFindOne$Params } from '../fn/backups/backup-controller-find-one';
import { backupControllerRemove } from '../fn/backups/backup-controller-remove';
import { BackupControllerRemove$Params } from '../fn/backups/backup-controller-remove';
import { backupControllerTrigger } from '../fn/backups/backup-controller-trigger';
import { BackupControllerTrigger$Params } from '../fn/backups/backup-controller-trigger';
import { BackupListResponse } from '../models/backup-list-response';
import { BackupResponse } from '../models/backup-response';
import { BackupTriggeredResponse } from '../models/backup-triggered-response';

@Injectable({ providedIn: 'root' })
export class BackupsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `backupControllerTrigger()` */
  static readonly BackupControllerTriggerPath = '/api/v1/backups/run';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `backupControllerTrigger()` instead.
   *
   * This method doesn't expect any request body.
   */
  backupControllerTrigger$Response(params?: BackupControllerTrigger$Params, context?: HttpContext): Promise<StrictHttpResponse<BackupTriggeredResponse>> {
    const obs = backupControllerTrigger(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `backupControllerTrigger$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  backupControllerTrigger(params?: BackupControllerTrigger$Params, context?: HttpContext): Promise<BackupTriggeredResponse> {
    const resp = this.backupControllerTrigger$Response(params, context);
    return resp.then((r: StrictHttpResponse<BackupTriggeredResponse>): BackupTriggeredResponse => r.body);
  }

  /** Path part for operation `backupControllerFindAll()` */
  static readonly BackupControllerFindAllPath = '/api/v1/backups';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `backupControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  backupControllerFindAll$Response(params?: BackupControllerFindAll$Params, context?: HttpContext): Promise<StrictHttpResponse<BackupListResponse>> {
    const obs = backupControllerFindAll(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `backupControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  backupControllerFindAll(params?: BackupControllerFindAll$Params, context?: HttpContext): Promise<BackupListResponse> {
    const resp = this.backupControllerFindAll$Response(params, context);
    return resp.then((r: StrictHttpResponse<BackupListResponse>): BackupListResponse => r.body);
  }

  /** Path part for operation `backupControllerExport()` */
  static readonly BackupControllerExportPath = '/api/v1/backups/export';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `backupControllerExport$Csv()` instead.
   *
   * This method doesn't expect any request body.
   */
  backupControllerExport$Csv$Response(params?: BackupControllerExport$Csv$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = backupControllerExport$Csv(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `backupControllerExport$Csv$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  backupControllerExport$Csv(params?: BackupControllerExport$Csv$Params, context?: HttpContext): Promise<any> {
    const resp = this.backupControllerExport$Csv$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `backupControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet()` instead.
   *
   * This method doesn't expect any request body.
   */
  backupControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Response(params?: BackupControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = backupControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `backupControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  backupControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet(params?: BackupControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Params, context?: HttpContext): Promise<any> {
    const resp = this.backupControllerExport$VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `backupControllerExport$Pdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  backupControllerExport$Pdf$Response(params?: BackupControllerExport$Pdf$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = backupControllerExport$Pdf(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `backupControllerExport$Pdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  backupControllerExport$Pdf(params?: BackupControllerExport$Pdf$Params, context?: HttpContext): Promise<any> {
    const resp = this.backupControllerExport$Pdf$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `backupControllerDownload()` */
  static readonly BackupControllerDownloadPath = '/api/v1/backups/{id}/download';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `backupControllerDownload()` instead.
   *
   * This method doesn't expect any request body.
   */
  backupControllerDownload$Response(params: BackupControllerDownload$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = backupControllerDownload(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `backupControllerDownload$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  backupControllerDownload(params: BackupControllerDownload$Params, context?: HttpContext): Promise<any> {
    const resp = this.backupControllerDownload$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `backupControllerFindOne()` */
  static readonly BackupControllerFindOnePath = '/api/v1/backups/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `backupControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  backupControllerFindOne$Response(params: BackupControllerFindOne$Params, context?: HttpContext): Promise<StrictHttpResponse<BackupResponse>> {
    const obs = backupControllerFindOne(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `backupControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  backupControllerFindOne(params: BackupControllerFindOne$Params, context?: HttpContext): Promise<BackupResponse> {
    const resp = this.backupControllerFindOne$Response(params, context);
    return resp.then((r: StrictHttpResponse<BackupResponse>): BackupResponse => r.body);
  }

  /** Path part for operation `backupControllerRemove()` */
  static readonly BackupControllerRemovePath = '/api/v1/backups/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `backupControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  backupControllerRemove$Response(params: BackupControllerRemove$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = backupControllerRemove(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `backupControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  backupControllerRemove(params: BackupControllerRemove$Params, context?: HttpContext): Promise<void> {
    const resp = this.backupControllerRemove$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
