/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { blogCategoryControllerBulkDelete } from '../fn/blog-categories/blog-category-controller-bulk-delete';
import { BlogCategoryControllerBulkDelete$Params } from '../fn/blog-categories/blog-category-controller-bulk-delete';
import { blogCategoryControllerBulkRestore } from '../fn/blog-categories/blog-category-controller-bulk-restore';
import { BlogCategoryControllerBulkRestore$Params } from '../fn/blog-categories/blog-category-controller-bulk-restore';
import { blogCategoryControllerCreate } from '../fn/blog-categories/blog-category-controller-create';
import { BlogCategoryControllerCreate$Params } from '../fn/blog-categories/blog-category-controller-create';
import { blogCategoryControllerDeleteImage } from '../fn/blog-categories/blog-category-controller-delete-image';
import { BlogCategoryControllerDeleteImage$Params } from '../fn/blog-categories/blog-category-controller-delete-image';
import { blogCategoryControllerExport } from '../fn/blog-categories/blog-category-controller-export';
import { BlogCategoryControllerExport$Params } from '../fn/blog-categories/blog-category-controller-export';
import { blogCategoryControllerFindAll } from '../fn/blog-categories/blog-category-controller-find-all';
import { BlogCategoryControllerFindAll$Params } from '../fn/blog-categories/blog-category-controller-find-all';
import { blogCategoryControllerFindOne } from '../fn/blog-categories/blog-category-controller-find-one';
import { BlogCategoryControllerFindOne$Params } from '../fn/blog-categories/blog-category-controller-find-one';
import { blogCategoryControllerFindTrash } from '../fn/blog-categories/blog-category-controller-find-trash';
import { BlogCategoryControllerFindTrash$Params } from '../fn/blog-categories/blog-category-controller-find-trash';
import { blogCategoryControllerRemove } from '../fn/blog-categories/blog-category-controller-remove';
import { BlogCategoryControllerRemove$Params } from '../fn/blog-categories/blog-category-controller-remove';
import { blogCategoryControllerRestore } from '../fn/blog-categories/blog-category-controller-restore';
import { BlogCategoryControllerRestore$Params } from '../fn/blog-categories/blog-category-controller-restore';
import { blogCategoryControllerUpdate } from '../fn/blog-categories/blog-category-controller-update';
import { BlogCategoryControllerUpdate$Params } from '../fn/blog-categories/blog-category-controller-update';
import { blogCategoryControllerUploadImage } from '../fn/blog-categories/blog-category-controller-upload-image';
import { BlogCategoryControllerUploadImage$Params } from '../fn/blog-categories/blog-category-controller-upload-image';
import { BlogCategoryResponse } from '../models/blog-category-response';

@Injectable({ providedIn: 'root' })
export class BlogCategoriesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `blogCategoryControllerFindAll()` */
  static readonly BlogCategoryControllerFindAllPath = '/api/v1/blog-categories';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `blogCategoryControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  blogCategoryControllerFindAll$Response(params?: BlogCategoryControllerFindAll$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<BlogCategoryResponse>>> {
    const obs = blogCategoryControllerFindAll(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `blogCategoryControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  blogCategoryControllerFindAll(params?: BlogCategoryControllerFindAll$Params, context?: HttpContext): Promise<Array<BlogCategoryResponse>> {
    const resp = this.blogCategoryControllerFindAll$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<BlogCategoryResponse>>): Array<BlogCategoryResponse> => r.body);
  }

  /** Path part for operation `blogCategoryControllerCreate()` */
  static readonly BlogCategoryControllerCreatePath = '/api/v1/blog-categories';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `blogCategoryControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  blogCategoryControllerCreate$Response(params: BlogCategoryControllerCreate$Params, context?: HttpContext): Promise<StrictHttpResponse<BlogCategoryResponse>> {
    const obs = blogCategoryControllerCreate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `blogCategoryControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  blogCategoryControllerCreate(params: BlogCategoryControllerCreate$Params, context?: HttpContext): Promise<BlogCategoryResponse> {
    const resp = this.blogCategoryControllerCreate$Response(params, context);
    return resp.then((r: StrictHttpResponse<BlogCategoryResponse>): BlogCategoryResponse => r.body);
  }

  /** Path part for operation `blogCategoryControllerFindTrash()` */
  static readonly BlogCategoryControllerFindTrashPath = '/api/v1/blog-categories/trash';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `blogCategoryControllerFindTrash()` instead.
   *
   * This method doesn't expect any request body.
   */
  blogCategoryControllerFindTrash$Response(params?: BlogCategoryControllerFindTrash$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<BlogCategoryResponse>>> {
    const obs = blogCategoryControllerFindTrash(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `blogCategoryControllerFindTrash$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  blogCategoryControllerFindTrash(params?: BlogCategoryControllerFindTrash$Params, context?: HttpContext): Promise<Array<BlogCategoryResponse>> {
    const resp = this.blogCategoryControllerFindTrash$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<BlogCategoryResponse>>): Array<BlogCategoryResponse> => r.body);
  }

  /** Path part for operation `blogCategoryControllerExport()` */
  static readonly BlogCategoryControllerExportPath = '/api/v1/blog-categories/export';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `blogCategoryControllerExport()` instead.
   *
   * This method doesn't expect any request body.
   */
  blogCategoryControllerExport$Response(params: BlogCategoryControllerExport$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = blogCategoryControllerExport(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `blogCategoryControllerExport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  blogCategoryControllerExport(params: BlogCategoryControllerExport$Params, context?: HttpContext): Promise<any> {
    const resp = this.blogCategoryControllerExport$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `blogCategoryControllerFindOne()` */
  static readonly BlogCategoryControllerFindOnePath = '/api/v1/blog-categories/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `blogCategoryControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  blogCategoryControllerFindOne$Response(params: BlogCategoryControllerFindOne$Params, context?: HttpContext): Promise<StrictHttpResponse<BlogCategoryResponse>> {
    const obs = blogCategoryControllerFindOne(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `blogCategoryControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  blogCategoryControllerFindOne(params: BlogCategoryControllerFindOne$Params, context?: HttpContext): Promise<BlogCategoryResponse> {
    const resp = this.blogCategoryControllerFindOne$Response(params, context);
    return resp.then((r: StrictHttpResponse<BlogCategoryResponse>): BlogCategoryResponse => r.body);
  }

  /** Path part for operation `blogCategoryControllerRemove()` */
  static readonly BlogCategoryControllerRemovePath = '/api/v1/blog-categories/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `blogCategoryControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  blogCategoryControllerRemove$Response(params: BlogCategoryControllerRemove$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = blogCategoryControllerRemove(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `blogCategoryControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  blogCategoryControllerRemove(params: BlogCategoryControllerRemove$Params, context?: HttpContext): Promise<void> {
    const resp = this.blogCategoryControllerRemove$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `blogCategoryControllerUpdate()` */
  static readonly BlogCategoryControllerUpdatePath = '/api/v1/blog-categories/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `blogCategoryControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  blogCategoryControllerUpdate$Response(params: BlogCategoryControllerUpdate$Params, context?: HttpContext): Promise<StrictHttpResponse<BlogCategoryResponse>> {
    const obs = blogCategoryControllerUpdate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `blogCategoryControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  blogCategoryControllerUpdate(params: BlogCategoryControllerUpdate$Params, context?: HttpContext): Promise<BlogCategoryResponse> {
    const resp = this.blogCategoryControllerUpdate$Response(params, context);
    return resp.then((r: StrictHttpResponse<BlogCategoryResponse>): BlogCategoryResponse => r.body);
  }

  /** Path part for operation `blogCategoryControllerRestore()` */
  static readonly BlogCategoryControllerRestorePath = '/api/v1/blog-categories/{id}/restore';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `blogCategoryControllerRestore()` instead.
   *
   * This method doesn't expect any request body.
   */
  blogCategoryControllerRestore$Response(params: BlogCategoryControllerRestore$Params, context?: HttpContext): Promise<StrictHttpResponse<BlogCategoryResponse>> {
    const obs = blogCategoryControllerRestore(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `blogCategoryControllerRestore$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  blogCategoryControllerRestore(params: BlogCategoryControllerRestore$Params, context?: HttpContext): Promise<BlogCategoryResponse> {
    const resp = this.blogCategoryControllerRestore$Response(params, context);
    return resp.then((r: StrictHttpResponse<BlogCategoryResponse>): BlogCategoryResponse => r.body);
  }

  /** Path part for operation `blogCategoryControllerBulkDelete()` */
  static readonly BlogCategoryControllerBulkDeletePath = '/api/v1/blog-categories/bulk-delete';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `blogCategoryControllerBulkDelete()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  blogCategoryControllerBulkDelete$Response(params: BlogCategoryControllerBulkDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = blogCategoryControllerBulkDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `blogCategoryControllerBulkDelete$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  blogCategoryControllerBulkDelete(params: BlogCategoryControllerBulkDelete$Params, context?: HttpContext): Promise<any> {
    const resp = this.blogCategoryControllerBulkDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `blogCategoryControllerBulkRestore()` */
  static readonly BlogCategoryControllerBulkRestorePath = '/api/v1/blog-categories/bulk-restore';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `blogCategoryControllerBulkRestore()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  blogCategoryControllerBulkRestore$Response(params: BlogCategoryControllerBulkRestore$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = blogCategoryControllerBulkRestore(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `blogCategoryControllerBulkRestore$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  blogCategoryControllerBulkRestore(params: BlogCategoryControllerBulkRestore$Params, context?: HttpContext): Promise<any> {
    const resp = this.blogCategoryControllerBulkRestore$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `blogCategoryControllerUploadImage()` */
  static readonly BlogCategoryControllerUploadImagePath = '/api/v1/blog-categories/{id}/image';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `blogCategoryControllerUploadImage()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  blogCategoryControllerUploadImage$Response(params: BlogCategoryControllerUploadImage$Params, context?: HttpContext): Promise<StrictHttpResponse<BlogCategoryResponse>> {
    const obs = blogCategoryControllerUploadImage(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `blogCategoryControllerUploadImage$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  blogCategoryControllerUploadImage(params: BlogCategoryControllerUploadImage$Params, context?: HttpContext): Promise<BlogCategoryResponse> {
    const resp = this.blogCategoryControllerUploadImage$Response(params, context);
    return resp.then((r: StrictHttpResponse<BlogCategoryResponse>): BlogCategoryResponse => r.body);
  }

  /** Path part for operation `blogCategoryControllerDeleteImage()` */
  static readonly BlogCategoryControllerDeleteImagePath = '/api/v1/blog-categories/{id}/image';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `blogCategoryControllerDeleteImage()` instead.
   *
   * This method doesn't expect any request body.
   */
  blogCategoryControllerDeleteImage$Response(params: BlogCategoryControllerDeleteImage$Params, context?: HttpContext): Promise<StrictHttpResponse<BlogCategoryResponse>> {
    const obs = blogCategoryControllerDeleteImage(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `blogCategoryControllerDeleteImage$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  blogCategoryControllerDeleteImage(params: BlogCategoryControllerDeleteImage$Params, context?: HttpContext): Promise<BlogCategoryResponse> {
    const resp = this.blogCategoryControllerDeleteImage$Response(params, context);
    return resp.then((r: StrictHttpResponse<BlogCategoryResponse>): BlogCategoryResponse => r.body);
  }

}
