/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CampaignExportListItemResponse } from '../models/campaign-export-list-item-response';
import { CampaignExportStatusResponse } from '../models/campaign-export-status-response';
import { campaignsControllerBulkDeleteCampaigns } from '../fn/campaigns/campaigns-controller-bulk-delete-campaigns';
import { CampaignsControllerBulkDeleteCampaigns$Params } from '../fn/campaigns/campaigns-controller-bulk-delete-campaigns';
import { campaignsControllerDeleteCampaign } from '../fn/campaigns/campaigns-controller-delete-campaign';
import { CampaignsControllerDeleteCampaign$Params } from '../fn/campaigns/campaigns-controller-delete-campaign';
import { campaignsControllerExportList } from '../fn/campaigns/campaigns-controller-export-list';
import { CampaignsControllerExportList$Params } from '../fn/campaigns/campaigns-controller-export-list';
import { campaignsControllerGenerateCampaign } from '../fn/campaigns/campaigns-controller-generate-campaign';
import { CampaignsControllerGenerateCampaign$Params } from '../fn/campaigns/campaigns-controller-generate-campaign';
import { campaignsControllerGenerateTopics } from '../fn/campaigns/campaigns-controller-generate-topics';
import { CampaignsControllerGenerateTopics$Params } from '../fn/campaigns/campaigns-controller-generate-topics';
import { campaignsControllerGetCampaign } from '../fn/campaigns/campaigns-controller-get-campaign';
import { CampaignsControllerGetCampaign$Params } from '../fn/campaigns/campaigns-controller-get-campaign';
import { campaignsControllerGetExportStatus } from '../fn/campaigns/campaigns-controller-get-export-status';
import { CampaignsControllerGetExportStatus$Params } from '../fn/campaigns/campaigns-controller-get-export-status';
import { campaignsControllerListCampaigns } from '../fn/campaigns/campaigns-controller-list-campaigns';
import { CampaignsControllerListCampaigns$Params } from '../fn/campaigns/campaigns-controller-list-campaigns';
import { campaignsControllerListExports } from '../fn/campaigns/campaigns-controller-list-exports';
import { CampaignsControllerListExports$Params } from '../fn/campaigns/campaigns-controller-list-exports';
import { campaignsControllerRequestExport } from '../fn/campaigns/campaigns-controller-request-export';
import { CampaignsControllerRequestExport$Params } from '../fn/campaigns/campaigns-controller-request-export';

@Injectable({ providedIn: 'root' })
export class CampaignsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `campaignsControllerGenerateTopics()` */
  static readonly CampaignsControllerGenerateTopicsPath = '/api/v1/campaigns/generate-topics';

  /**
   * Generate campaign topics (Step 1 of 2).
   *
   * Generates 10 campaign topics based on niche, location, and AI observations. Returns topics with scores for selection in Step 2.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `campaignsControllerGenerateTopics()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  campaignsControllerGenerateTopics$Response(params: CampaignsControllerGenerateTopics$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = campaignsControllerGenerateTopics(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Generate campaign topics (Step 1 of 2).
   *
   * Generates 10 campaign topics based on niche, location, and AI observations. Returns topics with scores for selection in Step 2.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `campaignsControllerGenerateTopics$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  campaignsControllerGenerateTopics(params: CampaignsControllerGenerateTopics$Params, context?: HttpContext): Promise<void> {
    const resp = this.campaignsControllerGenerateTopics$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `campaignsControllerGenerateCampaign()` */
  static readonly CampaignsControllerGenerateCampaignPath = '/api/v1/campaigns/generate-campaign';

  /**
   * Generate campaign from topic (Step 2 of 2).
   *
   * Creates a persisted CampaignGeneration and enqueues background processing. Real-time progress is delivered via WebSocket on the campaigns namespace. Rate limited to 3 requests per minute per user. Only super-admin may invoke (expensive AI pipeline).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `campaignsControllerGenerateCampaign()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  campaignsControllerGenerateCampaign$Response(params: CampaignsControllerGenerateCampaign$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = campaignsControllerGenerateCampaign(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Generate campaign from topic (Step 2 of 2).
   *
   * Creates a persisted CampaignGeneration and enqueues background processing. Real-time progress is delivered via WebSocket on the campaigns namespace. Rate limited to 3 requests per minute per user. Only super-admin may invoke (expensive AI pipeline).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `campaignsControllerGenerateCampaign$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  campaignsControllerGenerateCampaign(params: CampaignsControllerGenerateCampaign$Params, context?: HttpContext): Promise<void> {
    const resp = this.campaignsControllerGenerateCampaign$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `campaignsControllerRequestExport()` */
  static readonly CampaignsControllerRequestExportPath = '/api/v1/campaigns/export';

  /**
   * Request campaign video export (TOFU/MOFU/BOFU/LOYALTY).
   *
   * Creates a persisted CampaignGeneration and enqueues background processing. Real-time progress is delivered via WebSocket on the campaigns namespace. Rate limited to 3 requests per minute per user. Only super-admin may invoke (expensive AI pipeline).
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `campaignsControllerRequestExport()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  campaignsControllerRequestExport$Response(params: CampaignsControllerRequestExport$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = campaignsControllerRequestExport(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Request campaign video export (TOFU/MOFU/BOFU/LOYALTY).
   *
   * Creates a persisted CampaignGeneration and enqueues background processing. Real-time progress is delivered via WebSocket on the campaigns namespace. Rate limited to 3 requests per minute per user. Only super-admin may invoke (expensive AI pipeline).
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `campaignsControllerRequestExport$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  campaignsControllerRequestExport(params: CampaignsControllerRequestExport$Params, context?: HttpContext): Promise<void> {
    const resp = this.campaignsControllerRequestExport$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `campaignsControllerGetExportStatus()` */
  static readonly CampaignsControllerGetExportStatusPath = '/api/v1/campaigns/export/{id}';

  /**
   * Get status and download links for a campaign export.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `campaignsControllerGetExportStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  campaignsControllerGetExportStatus$Response(params: CampaignsControllerGetExportStatus$Params, context?: HttpContext): Promise<StrictHttpResponse<CampaignExportStatusResponse>> {
    const obs = campaignsControllerGetExportStatus(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get status and download links for a campaign export.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `campaignsControllerGetExportStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  campaignsControllerGetExportStatus(params: CampaignsControllerGetExportStatus$Params, context?: HttpContext): Promise<CampaignExportStatusResponse> {
    const resp = this.campaignsControllerGetExportStatus$Response(params, context);
    return resp.then((r: StrictHttpResponse<CampaignExportStatusResponse>): CampaignExportStatusResponse => r.body);
  }

  /** Path part for operation `campaignsControllerListExports()` */
  static readonly CampaignsControllerListExportsPath = '/api/v1/campaigns/exports';

  /**
   * List my campaign exports.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `campaignsControllerListExports()` instead.
   *
   * This method doesn't expect any request body.
   */
  campaignsControllerListExports$Response(params?: CampaignsControllerListExports$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<CampaignExportListItemResponse>>> {
    const obs = campaignsControllerListExports(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List my campaign exports.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `campaignsControllerListExports$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  campaignsControllerListExports(params?: CampaignsControllerListExports$Params, context?: HttpContext): Promise<Array<CampaignExportListItemResponse>> {
    const resp = this.campaignsControllerListExports$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<CampaignExportListItemResponse>>): Array<CampaignExportListItemResponse> => r.body);
  }

  /** Path part for operation `campaignsControllerExportList()` */
  static readonly CampaignsControllerExportListPath = '/api/v1/campaigns/exports/export';

  /**
   * Export campaign generation history as file.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `campaignsControllerExportList()` instead.
   *
   * This method doesn't expect any request body.
   */
  campaignsControllerExportList$Response(params?: CampaignsControllerExportList$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = campaignsControllerExportList(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Export campaign generation history as file.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `campaignsControllerExportList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  campaignsControllerExportList(params?: CampaignsControllerExportList$Params, context?: HttpContext): Promise<any> {
    const resp = this.campaignsControllerExportList$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `campaignsControllerListCampaigns()` */
  static readonly CampaignsControllerListCampaignsPath = '/api/v1/campaigns';

  /**
   * List campaign generations.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `campaignsControllerListCampaigns()` instead.
   *
   * This method doesn't expect any request body.
   */
  campaignsControllerListCampaigns$Response(params?: CampaignsControllerListCampaigns$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<CampaignExportListItemResponse>>> {
    const obs = campaignsControllerListCampaigns(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * List campaign generations.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `campaignsControllerListCampaigns$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  campaignsControllerListCampaigns(params?: CampaignsControllerListCampaigns$Params, context?: HttpContext): Promise<Array<CampaignExportListItemResponse>> {
    const resp = this.campaignsControllerListCampaigns$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<CampaignExportListItemResponse>>): Array<CampaignExportListItemResponse> => r.body);
  }

  /** Path part for operation `campaignsControllerGetCampaign()` */
  static readonly CampaignsControllerGetCampaignPath = '/api/v1/campaigns/{id}';

  /**
   * Get campaign generation details.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `campaignsControllerGetCampaign()` instead.
   *
   * This method doesn't expect any request body.
   */
  campaignsControllerGetCampaign$Response(params: CampaignsControllerGetCampaign$Params, context?: HttpContext): Promise<StrictHttpResponse<CampaignExportStatusResponse>> {
    const obs = campaignsControllerGetCampaign(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Get campaign generation details.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `campaignsControllerGetCampaign$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  campaignsControllerGetCampaign(params: CampaignsControllerGetCampaign$Params, context?: HttpContext): Promise<CampaignExportStatusResponse> {
    const resp = this.campaignsControllerGetCampaign$Response(params, context);
    return resp.then((r: StrictHttpResponse<CampaignExportStatusResponse>): CampaignExportStatusResponse => r.body);
  }

  /** Path part for operation `campaignsControllerDeleteCampaign()` */
  static readonly CampaignsControllerDeleteCampaignPath = '/api/v1/campaigns/{id}';

  /**
   * Delete campaign generation (hard delete).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `campaignsControllerDeleteCampaign()` instead.
   *
   * This method doesn't expect any request body.
   */
  campaignsControllerDeleteCampaign$Response(params: CampaignsControllerDeleteCampaign$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = campaignsControllerDeleteCampaign(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Delete campaign generation (hard delete).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `campaignsControllerDeleteCampaign$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  campaignsControllerDeleteCampaign(params: CampaignsControllerDeleteCampaign$Params, context?: HttpContext): Promise<void> {
    const resp = this.campaignsControllerDeleteCampaign$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `campaignsControllerBulkDeleteCampaigns()` */
  static readonly CampaignsControllerBulkDeleteCampaignsPath = '/api/v1/campaigns/bulk-delete';

  /**
   * Bulk delete campaign generations (hard delete).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `campaignsControllerBulkDeleteCampaigns()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  campaignsControllerBulkDeleteCampaigns$Response(params: CampaignsControllerBulkDeleteCampaigns$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = campaignsControllerBulkDeleteCampaigns(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Bulk delete campaign generations (hard delete).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `campaignsControllerBulkDeleteCampaigns$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  campaignsControllerBulkDeleteCampaigns(params: CampaignsControllerBulkDeleteCampaigns$Params, context?: HttpContext): Promise<void> {
    const resp = this.campaignsControllerBulkDeleteCampaigns$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
