/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { companyDataControllerDeleteSignature } from '../fn/company-data/company-data-controller-delete-signature';
import { CompanyDataControllerDeleteSignature$Params } from '../fn/company-data/company-data-controller-delete-signature';
import { companyDataControllerFindOne } from '../fn/company-data/company-data-controller-find-one';
import { CompanyDataControllerFindOne$Params } from '../fn/company-data/company-data-controller-find-one';
import { companyDataControllerFindPublic } from '../fn/company-data/company-data-controller-find-public';
import { CompanyDataControllerFindPublic$Params } from '../fn/company-data/company-data-controller-find-public';
import { companyDataControllerFindSingleton } from '../fn/company-data/company-data-controller-find-singleton';
import { CompanyDataControllerFindSingleton$Params } from '../fn/company-data/company-data-controller-find-singleton';
import { companyDataControllerGetMyCompanyData } from '../fn/company-data/company-data-controller-get-my-company-data';
import { CompanyDataControllerGetMyCompanyData$Params } from '../fn/company-data/company-data-controller-get-my-company-data';
import { companyDataControllerUpdate } from '../fn/company-data/company-data-controller-update';
import { CompanyDataControllerUpdate$Params } from '../fn/company-data/company-data-controller-update';
import { companyDataControllerUploadSignature } from '../fn/company-data/company-data-controller-upload-signature';
import { CompanyDataControllerUploadSignature$Params } from '../fn/company-data/company-data-controller-upload-signature';
import { CompanyDataResponse } from '../models/company-data-response';

@Injectable({ providedIn: 'root' })
export class CompanyDataService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `companyDataControllerFindPublic()` */
  static readonly CompanyDataControllerFindPublicPath = '/api/v1/company-data/public';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `companyDataControllerFindPublic()` instead.
   *
   * This method doesn't expect any request body.
   */
  companyDataControllerFindPublic$Response(params?: CompanyDataControllerFindPublic$Params, context?: HttpContext): Promise<StrictHttpResponse<CompanyDataResponse>> {
    const obs = companyDataControllerFindPublic(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `companyDataControllerFindPublic$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  companyDataControllerFindPublic(params?: CompanyDataControllerFindPublic$Params, context?: HttpContext): Promise<CompanyDataResponse> {
    const resp = this.companyDataControllerFindPublic$Response(params, context);
    return resp.then((r: StrictHttpResponse<CompanyDataResponse>): CompanyDataResponse => r.body);
  }

  /** Path part for operation `companyDataControllerFindSingleton()` */
  static readonly CompanyDataControllerFindSingletonPath = '/api/v1/company-data';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `companyDataControllerFindSingleton()` instead.
   *
   * This method doesn't expect any request body.
   */
  companyDataControllerFindSingleton$Response(params?: CompanyDataControllerFindSingleton$Params, context?: HttpContext): Promise<StrictHttpResponse<CompanyDataResponse>> {
    const obs = companyDataControllerFindSingleton(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `companyDataControllerFindSingleton$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  companyDataControllerFindSingleton(params?: CompanyDataControllerFindSingleton$Params, context?: HttpContext): Promise<CompanyDataResponse> {
    const resp = this.companyDataControllerFindSingleton$Response(params, context);
    return resp.then((r: StrictHttpResponse<CompanyDataResponse>): CompanyDataResponse => r.body);
  }

  /** Path part for operation `companyDataControllerGetMyCompanyData()` */
  static readonly CompanyDataControllerGetMyCompanyDataPath = '/api/v1/company-data/me';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `companyDataControllerGetMyCompanyData()` instead.
   *
   * This method doesn't expect any request body.
   */
  companyDataControllerGetMyCompanyData$Response(params?: CompanyDataControllerGetMyCompanyData$Params, context?: HttpContext): Promise<StrictHttpResponse<CompanyDataResponse>> {
    const obs = companyDataControllerGetMyCompanyData(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `companyDataControllerGetMyCompanyData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  companyDataControllerGetMyCompanyData(params?: CompanyDataControllerGetMyCompanyData$Params, context?: HttpContext): Promise<CompanyDataResponse> {
    const resp = this.companyDataControllerGetMyCompanyData$Response(params, context);
    return resp.then((r: StrictHttpResponse<CompanyDataResponse>): CompanyDataResponse => r.body);
  }

  /** Path part for operation `companyDataControllerFindOne()` */
  static readonly CompanyDataControllerFindOnePath = '/api/v1/company-data/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `companyDataControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  companyDataControllerFindOne$Response(params: CompanyDataControllerFindOne$Params, context?: HttpContext): Promise<StrictHttpResponse<CompanyDataResponse>> {
    const obs = companyDataControllerFindOne(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `companyDataControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  companyDataControllerFindOne(params: CompanyDataControllerFindOne$Params, context?: HttpContext): Promise<CompanyDataResponse> {
    const resp = this.companyDataControllerFindOne$Response(params, context);
    return resp.then((r: StrictHttpResponse<CompanyDataResponse>): CompanyDataResponse => r.body);
  }

  /** Path part for operation `companyDataControllerUpdate()` */
  static readonly CompanyDataControllerUpdatePath = '/api/v1/company-data/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `companyDataControllerUpdate()` instead.
   *
   * This method doesn't expect any request body.
   */
  companyDataControllerUpdate$Response(params: CompanyDataControllerUpdate$Params, context?: HttpContext): Promise<StrictHttpResponse<CompanyDataResponse>> {
    const obs = companyDataControllerUpdate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `companyDataControllerUpdate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  companyDataControllerUpdate(params: CompanyDataControllerUpdate$Params, context?: HttpContext): Promise<CompanyDataResponse> {
    const resp = this.companyDataControllerUpdate$Response(params, context);
    return resp.then((r: StrictHttpResponse<CompanyDataResponse>): CompanyDataResponse => r.body);
  }

  /** Path part for operation `companyDataControllerUploadSignature()` */
  static readonly CompanyDataControllerUploadSignaturePath = '/api/v1/company-data/{id}/signature';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `companyDataControllerUploadSignature()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  companyDataControllerUploadSignature$Response(params: CompanyDataControllerUploadSignature$Params, context?: HttpContext): Promise<StrictHttpResponse<CompanyDataResponse>> {
    const obs = companyDataControllerUploadSignature(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `companyDataControllerUploadSignature$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  companyDataControllerUploadSignature(params: CompanyDataControllerUploadSignature$Params, context?: HttpContext): Promise<CompanyDataResponse> {
    const resp = this.companyDataControllerUploadSignature$Response(params, context);
    return resp.then((r: StrictHttpResponse<CompanyDataResponse>): CompanyDataResponse => r.body);
  }

  /** Path part for operation `companyDataControllerDeleteSignature()` */
  static readonly CompanyDataControllerDeleteSignaturePath = '/api/v1/company-data/{id}/signature';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `companyDataControllerDeleteSignature()` instead.
   *
   * This method doesn't expect any request body.
   */
  companyDataControllerDeleteSignature$Response(params: CompanyDataControllerDeleteSignature$Params, context?: HttpContext): Promise<StrictHttpResponse<CompanyDataResponse>> {
    const obs = companyDataControllerDeleteSignature(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `companyDataControllerDeleteSignature$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  companyDataControllerDeleteSignature(params: CompanyDataControllerDeleteSignature$Params, context?: HttpContext): Promise<CompanyDataResponse> {
    const resp = this.companyDataControllerDeleteSignature$Response(params, context);
    return resp.then((r: StrictHttpResponse<CompanyDataResponse>): CompanyDataResponse => r.body);
  }

}
