/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { contactSupportControllerBulkDelete } from '../fn/contact-support/contact-support-controller-bulk-delete';
import { ContactSupportControllerBulkDelete$Params } from '../fn/contact-support/contact-support-controller-bulk-delete';
import { contactSupportControllerBulkRestore } from '../fn/contact-support/contact-support-controller-bulk-restore';
import { ContactSupportControllerBulkRestore$Params } from '../fn/contact-support/contact-support-controller-bulk-restore';
import { contactSupportControllerCreate } from '../fn/contact-support/contact-support-controller-create';
import { ContactSupportControllerCreate$Params } from '../fn/contact-support/contact-support-controller-create';
import { contactSupportControllerExport$Csv } from '../fn/contact-support/contact-support-controller-export-csv';
import { ContactSupportControllerExport$Csv$Params } from '../fn/contact-support/contact-support-controller-export-csv';
import { contactSupportControllerExport$Pdf } from '../fn/contact-support/contact-support-controller-export-pdf';
import { ContactSupportControllerExport$Pdf$Params } from '../fn/contact-support/contact-support-controller-export-pdf';
import { contactSupportControllerFindOne } from '../fn/contact-support/contact-support-controller-find-one';
import { ContactSupportControllerFindOne$Params } from '../fn/contact-support/contact-support-controller-find-one';
import { contactSupportControllerList } from '../fn/contact-support/contact-support-controller-list';
import { ContactSupportControllerList$Params } from '../fn/contact-support/contact-support-controller-list';
import { contactSupportControllerMarkAsRead } from '../fn/contact-support/contact-support-controller-mark-as-read';
import { ContactSupportControllerMarkAsRead$Params } from '../fn/contact-support/contact-support-controller-mark-as-read';
import { contactSupportControllerRemove } from '../fn/contact-support/contact-support-controller-remove';
import { ContactSupportControllerRemove$Params } from '../fn/contact-support/contact-support-controller-remove';
import { contactSupportControllerRestore } from '../fn/contact-support/contact-support-controller-restore';
import { ContactSupportControllerRestore$Params } from '../fn/contact-support/contact-support-controller-restore';
import { ContactSupportListResponse } from '../models/contact-support-list-response';
import { ContactSupportResponse } from '../models/contact-support-response';
import { CreateContactSupportResponse } from '../models/create-contact-support-response';

@Injectable({ providedIn: 'root' })
export class ContactSupportService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `contactSupportControllerList()` */
  static readonly ContactSupportControllerListPath = '/api/v1/contact-support';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contactSupportControllerList()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactSupportControllerList$Response(params?: ContactSupportControllerList$Params, context?: HttpContext): Promise<StrictHttpResponse<ContactSupportListResponse>> {
    const obs = contactSupportControllerList(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contactSupportControllerList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactSupportControllerList(params?: ContactSupportControllerList$Params, context?: HttpContext): Promise<ContactSupportListResponse> {
    const resp = this.contactSupportControllerList$Response(params, context);
    return resp.then((r: StrictHttpResponse<ContactSupportListResponse>): ContactSupportListResponse => r.body);
  }

  /** Path part for operation `contactSupportControllerCreate()` */
  static readonly ContactSupportControllerCreatePath = '/api/v1/contact-support';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contactSupportControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  contactSupportControllerCreate$Response(params: ContactSupportControllerCreate$Params, context?: HttpContext): Promise<StrictHttpResponse<CreateContactSupportResponse>> {
    const obs = contactSupportControllerCreate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contactSupportControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  contactSupportControllerCreate(params: ContactSupportControllerCreate$Params, context?: HttpContext): Promise<CreateContactSupportResponse> {
    const resp = this.contactSupportControllerCreate$Response(params, context);
    return resp.then((r: StrictHttpResponse<CreateContactSupportResponse>): CreateContactSupportResponse => r.body);
  }

  /** Path part for operation `contactSupportControllerExport()` */
  static readonly ContactSupportControllerExportPath = '/api/v1/contact-support/export';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contactSupportControllerExport$Csv()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactSupportControllerExport$Csv$Response(params?: ContactSupportControllerExport$Csv$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = contactSupportControllerExport$Csv(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contactSupportControllerExport$Csv$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactSupportControllerExport$Csv(params?: ContactSupportControllerExport$Csv$Params, context?: HttpContext): Promise<any> {
    const resp = this.contactSupportControllerExport$Csv$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contactSupportControllerExport$Pdf()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactSupportControllerExport$Pdf$Response(params?: ContactSupportControllerExport$Pdf$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = contactSupportControllerExport$Pdf(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contactSupportControllerExport$Pdf$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactSupportControllerExport$Pdf(params?: ContactSupportControllerExport$Pdf$Params, context?: HttpContext): Promise<any> {
    const resp = this.contactSupportControllerExport$Pdf$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `contactSupportControllerFindOne()` */
  static readonly ContactSupportControllerFindOnePath = '/api/v1/contact-support/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contactSupportControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactSupportControllerFindOne$Response(params: ContactSupportControllerFindOne$Params, context?: HttpContext): Promise<StrictHttpResponse<ContactSupportResponse>> {
    const obs = contactSupportControllerFindOne(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contactSupportControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactSupportControllerFindOne(params: ContactSupportControllerFindOne$Params, context?: HttpContext): Promise<ContactSupportResponse> {
    const resp = this.contactSupportControllerFindOne$Response(params, context);
    return resp.then((r: StrictHttpResponse<ContactSupportResponse>): ContactSupportResponse => r.body);
  }

  /** Path part for operation `contactSupportControllerRemove()` */
  static readonly ContactSupportControllerRemovePath = '/api/v1/contact-support/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contactSupportControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactSupportControllerRemove$Response(params: ContactSupportControllerRemove$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = contactSupportControllerRemove(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contactSupportControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactSupportControllerRemove(params: ContactSupportControllerRemove$Params, context?: HttpContext): Promise<void> {
    const resp = this.contactSupportControllerRemove$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `contactSupportControllerMarkAsRead()` */
  static readonly ContactSupportControllerMarkAsReadPath = '/api/v1/contact-support/{id}/read';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contactSupportControllerMarkAsRead()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactSupportControllerMarkAsRead$Response(params: ContactSupportControllerMarkAsRead$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = contactSupportControllerMarkAsRead(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contactSupportControllerMarkAsRead$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactSupportControllerMarkAsRead(params: ContactSupportControllerMarkAsRead$Params, context?: HttpContext): Promise<void> {
    const resp = this.contactSupportControllerMarkAsRead$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `contactSupportControllerRestore()` */
  static readonly ContactSupportControllerRestorePath = '/api/v1/contact-support/{id}/restore';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contactSupportControllerRestore()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactSupportControllerRestore$Response(params: ContactSupportControllerRestore$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = contactSupportControllerRestore(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contactSupportControllerRestore$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactSupportControllerRestore(params: ContactSupportControllerRestore$Params, context?: HttpContext): Promise<void> {
    const resp = this.contactSupportControllerRestore$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `contactSupportControllerBulkDelete()` */
  static readonly ContactSupportControllerBulkDeletePath = '/api/v1/contact-support/bulk-delete';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contactSupportControllerBulkDelete()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  contactSupportControllerBulkDelete$Response(params: ContactSupportControllerBulkDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = contactSupportControllerBulkDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contactSupportControllerBulkDelete$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  contactSupportControllerBulkDelete(params: ContactSupportControllerBulkDelete$Params, context?: HttpContext): Promise<any> {
    const resp = this.contactSupportControllerBulkDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `contactSupportControllerBulkRestore()` */
  static readonly ContactSupportControllerBulkRestorePath = '/api/v1/contact-support/bulk-restore';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contactSupportControllerBulkRestore()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  contactSupportControllerBulkRestore$Response(params: ContactSupportControllerBulkRestore$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = contactSupportControllerBulkRestore(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contactSupportControllerBulkRestore$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  contactSupportControllerBulkRestore(params: ContactSupportControllerBulkRestore$Params, context?: HttpContext): Promise<any> {
    const resp = this.contactSupportControllerBulkRestore$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

}
