/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CreatePostResponse } from '../models/create-post-response';
import { GeneratePostPreviewResponse } from '../models/generate-post-preview-response';
import { GenerateSocialIdeasResponse } from '../models/generate-social-ideas-response';
import { GenerateSocialPostResponse } from '../models/generate-social-post-response';
import { PostListResponse } from '../models/post-list-response';
import { PostResponse } from '../models/post-response';
import { postsControllerBulkDelete } from '../fn/posts/posts-controller-bulk-delete';
import { PostsControllerBulkDelete$Params } from '../fn/posts/posts-controller-bulk-delete';
import { postsControllerBulkRestore } from '../fn/posts/posts-controller-bulk-restore';
import { PostsControllerBulkRestore$Params } from '../fn/posts/posts-controller-bulk-restore';
import { postsControllerCreate } from '../fn/posts/posts-controller-create';
import { PostsControllerCreate$Params } from '../fn/posts/posts-controller-create';
import { postsControllerDelete } from '../fn/posts/posts-controller-delete';
import { PostsControllerDelete$Params } from '../fn/posts/posts-controller-delete';
import { postsControllerDownloadSocialZip } from '../fn/posts/posts-controller-download-social-zip';
import { PostsControllerDownloadSocialZip$Params } from '../fn/posts/posts-controller-download-social-zip';
import { postsControllerExport } from '../fn/posts/posts-controller-export';
import { PostsControllerExport$Params } from '../fn/posts/posts-controller-export';
import { postsControllerFindAll } from '../fn/posts/posts-controller-find-all';
import { PostsControllerFindAll$Params } from '../fn/posts/posts-controller-find-all';
import { postsControllerFindOne } from '../fn/posts/posts-controller-find-one';
import { PostsControllerFindOne$Params } from '../fn/posts/posts-controller-find-one';
import { postsControllerGeneratePreview } from '../fn/posts/posts-controller-generate-preview';
import { PostsControllerGeneratePreview$Params } from '../fn/posts/posts-controller-generate-preview';
import { postsControllerGenerateSocialPost } from '../fn/posts/posts-controller-generate-social-post';
import { PostsControllerGenerateSocialPost$Params } from '../fn/posts/posts-controller-generate-social-post';
import { postsControllerGenerateSocialPostIdeas } from '../fn/posts/posts-controller-generate-social-post-ideas';
import { PostsControllerGenerateSocialPostIdeas$Params } from '../fn/posts/posts-controller-generate-social-post-ideas';
import { postsControllerRestore } from '../fn/posts/posts-controller-restore';
import { PostsControllerRestore$Params } from '../fn/posts/posts-controller-restore';
import { postsControllerUpdate } from '../fn/posts/posts-controller-update';
import { PostsControllerUpdate$Params } from '../fn/posts/posts-controller-update';

@Injectable({ providedIn: 'root' })
export class PostsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `postsControllerFindAll()` */
  static readonly PostsControllerFindAllPath = '/api/v1/posts';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `postsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  postsControllerFindAll$Response(params?: PostsControllerFindAll$Params, context?: HttpContext): Promise<StrictHttpResponse<PostListResponse>> {
    const obs = postsControllerFindAll(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `postsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  postsControllerFindAll(params?: PostsControllerFindAll$Params, context?: HttpContext): Promise<PostListResponse> {
    const resp = this.postsControllerFindAll$Response(params, context);
    return resp.then((r: StrictHttpResponse<PostListResponse>): PostListResponse => r.body);
  }

  /** Path part for operation `postsControllerCreate()` */
  static readonly PostsControllerCreatePath = '/api/v1/posts';

  /**
   * Create a new post (manual or AI-assisted).
   *
   * Creates a blog post.
   *
   * Two mutually compatible flows:
   *
   * 1. Manual creation — client provides full postContent + SEO fields.
   *
   * 2. AI-assisted creation (recommended for speed) — set `generateWithAi: true`. The backend will:
   *    - Call Tavily for fresh research (E-E-A-T grounding)
   *    - Generate the full Markdown article + SEO fields with Gemini using the official 10 E-E-A-T writing rules
   *    - Optionally generate and upload a hero image to R2
   *    - All generation + external side-effects happen BEFORE the database transaction.
   *
   * Client-provided values always override AI-generated ones (postContent, SEO fields, postCoverImage).
   *
   * When using the AI flow you only need to send the title + generateWithAi (niche and wordCount are optional).
   *
   * Requires valid GEMINI_API_KEY and TAVILY_API_KEY when generateWithAi is true.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `postsControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  postsControllerCreate$Response(params: PostsControllerCreate$Params, context?: HttpContext): Promise<StrictHttpResponse<CreatePostResponse>> {
    const obs = postsControllerCreate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Create a new post (manual or AI-assisted).
   *
   * Creates a blog post.
   *
   * Two mutually compatible flows:
   *
   * 1. Manual creation — client provides full postContent + SEO fields.
   *
   * 2. AI-assisted creation (recommended for speed) — set `generateWithAi: true`. The backend will:
   *    - Call Tavily for fresh research (E-E-A-T grounding)
   *    - Generate the full Markdown article + SEO fields with Gemini using the official 10 E-E-A-T writing rules
   *    - Optionally generate and upload a hero image to R2
   *    - All generation + external side-effects happen BEFORE the database transaction.
   *
   * Client-provided values always override AI-generated ones (postContent, SEO fields, postCoverImage).
   *
   * When using the AI flow you only need to send the title + generateWithAi (niche and wordCount are optional).
   *
   * Requires valid GEMINI_API_KEY and TAVILY_API_KEY when generateWithAi is true.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `postsControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  postsControllerCreate(params: PostsControllerCreate$Params, context?: HttpContext): Promise<CreatePostResponse> {
    const resp = this.postsControllerCreate$Response(params, context);
    return resp.then((r: StrictHttpResponse<CreatePostResponse>): CreatePostResponse => r.body);
  }

  /** Path part for operation `postsControllerGeneratePreview()` */
  static readonly PostsControllerGeneratePreviewPath = '/api/v1/posts/ai/generate-preview';

  /**
   * Generate post content with AI (Gemini + Tavily research).
   *
   * Triggers a full AI content generation pipeline for a blog post.
   *
   * The system performs:
   * 1. Web research via Tavily (E-E-A-T grounding)
   * 2. Article generation with Google Gemini using the exact 10 E-E-A-T writing rules and SEO structure from the content pipeline spec
   * 3. SEO metadata generation (slug, excerpt, meta title/description/keywords)
   * 4. Hero image generation (when supported by the model) and upload to R2
   *
   * The generated content is returned for human review/editing before final submission.
   *
   * Rate limited to 5 requests per 60 seconds.
   *
   * Requires valid GEMINI_API_KEY and TAVILY_API_KEY.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `postsControllerGeneratePreview()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  postsControllerGeneratePreview$Response(params: PostsControllerGeneratePreview$Params, context?: HttpContext): Promise<StrictHttpResponse<GeneratePostPreviewResponse>> {
    const obs = postsControllerGeneratePreview(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Generate post content with AI (Gemini + Tavily research).
   *
   * Triggers a full AI content generation pipeline for a blog post.
   *
   * The system performs:
   * 1. Web research via Tavily (E-E-A-T grounding)
   * 2. Article generation with Google Gemini using the exact 10 E-E-A-T writing rules and SEO structure from the content pipeline spec
   * 3. SEO metadata generation (slug, excerpt, meta title/description/keywords)
   * 4. Hero image generation (when supported by the model) and upload to R2
   *
   * The generated content is returned for human review/editing before final submission.
   *
   * Rate limited to 5 requests per 60 seconds.
   *
   * Requires valid GEMINI_API_KEY and TAVILY_API_KEY.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `postsControllerGeneratePreview$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  postsControllerGeneratePreview(params: PostsControllerGeneratePreview$Params, context?: HttpContext): Promise<GeneratePostPreviewResponse> {
    const resp = this.postsControllerGeneratePreview$Response(params, context);
    return resp.then((r: StrictHttpResponse<GeneratePostPreviewResponse>): GeneratePostPreviewResponse => r.body);
  }

  /** Path part for operation `postsControllerGenerateSocialPostIdeas()` */
  static readonly PostsControllerGenerateSocialPostIdeasPath = '/api/v1/posts/social/generate-ideas';

  /**
   * Generate 10 viral social media content ideas.
   *
   * Generates 10 content ideas for social media platforms with virality, ROI, and EEAT scoring.
   *
   * Supports multiple AI providers (Gemini, Anthropic, OpenAI) based on configuration.
   *
   * Rate limited to 10 requests per 60 seconds.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `postsControllerGenerateSocialPostIdeas()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  postsControllerGenerateSocialPostIdeas$Response(params: PostsControllerGenerateSocialPostIdeas$Params, context?: HttpContext): Promise<StrictHttpResponse<GenerateSocialIdeasResponse>> {
    const obs = postsControllerGenerateSocialPostIdeas(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Generate 10 viral social media content ideas.
   *
   * Generates 10 content ideas for social media platforms with virality, ROI, and EEAT scoring.
   *
   * Supports multiple AI providers (Gemini, Anthropic, OpenAI) based on configuration.
   *
   * Rate limited to 10 requests per 60 seconds.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `postsControllerGenerateSocialPostIdeas$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  postsControllerGenerateSocialPostIdeas(params: PostsControllerGenerateSocialPostIdeas$Params, context?: HttpContext): Promise<GenerateSocialIdeasResponse> {
    const resp = this.postsControllerGenerateSocialPostIdeas$Response(params, context);
    return resp.then((r: StrictHttpResponse<GenerateSocialIdeasResponse>): GenerateSocialIdeasResponse => r.body);
  }

  /** Path part for operation `postsControllerGenerateSocialPost()` */
  static readonly PostsControllerGenerateSocialPostPath = '/api/v1/posts/social/generate-post';

  /**
   * Generate complete social media post with platform variations.
   *
   * Generates a complete social media post with platform-specific variations, SEO metadata, and quality scores.
   *
   * Supports multiple AI providers (Gemini, Anthropic, OpenAI).
   *
   * Includes:
   * - Platform variations (Blog, LinkedIn, Twitter/X, Newsletter, Facebook)
   * - SEO metadata (meta tags, Open Graph, Twitter Cards, Schema.org JSON-LD)
   * - Quality scores (Human Writing, EEAT, Virality, ROI, SEO)
   * - Image generation prompts for Gemini Imagen
   *
   * Rate limited to 5 requests per 60 seconds.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `postsControllerGenerateSocialPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  postsControllerGenerateSocialPost$Response(params: PostsControllerGenerateSocialPost$Params, context?: HttpContext): Promise<StrictHttpResponse<GenerateSocialPostResponse>> {
    const obs = postsControllerGenerateSocialPost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Generate complete social media post with platform variations.
   *
   * Generates a complete social media post with platform-specific variations, SEO metadata, and quality scores.
   *
   * Supports multiple AI providers (Gemini, Anthropic, OpenAI).
   *
   * Includes:
   * - Platform variations (Blog, LinkedIn, Twitter/X, Newsletter, Facebook)
   * - SEO metadata (meta tags, Open Graph, Twitter Cards, Schema.org JSON-LD)
   * - Quality scores (Human Writing, EEAT, Virality, ROI, SEO)
   * - Image generation prompts for Gemini Imagen
   *
   * Rate limited to 5 requests per 60 seconds.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `postsControllerGenerateSocialPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  postsControllerGenerateSocialPost(params: PostsControllerGenerateSocialPost$Params, context?: HttpContext): Promise<GenerateSocialPostResponse> {
    const resp = this.postsControllerGenerateSocialPost$Response(params, context);
    return resp.then((r: StrictHttpResponse<GenerateSocialPostResponse>): GenerateSocialPostResponse => r.body);
  }

  /** Path part for operation `postsControllerDownloadSocialZip()` */
  static readonly PostsControllerDownloadSocialZipPath = '/api/v1/posts/social/{id}/download-zip';

  /**
   * Download a generated social-media package as a ZIP.
   *
   * Streams a ZIP archive (content/, seo/, metadata/, images/, README) for a previously generated social-media package. Owner-only.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `postsControllerDownloadSocialZip()` instead.
   *
   * This method doesn't expect any request body.
   */
  postsControllerDownloadSocialZip$Response(params: PostsControllerDownloadSocialZip$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = postsControllerDownloadSocialZip(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * Download a generated social-media package as a ZIP.
   *
   * Streams a ZIP archive (content/, seo/, metadata/, images/, README) for a previously generated social-media package. Owner-only.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `postsControllerDownloadSocialZip$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  postsControllerDownloadSocialZip(params: PostsControllerDownloadSocialZip$Params, context?: HttpContext): Promise<void> {
    const resp = this.postsControllerDownloadSocialZip$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `postsControllerExport()` */
  static readonly PostsControllerExportPath = '/api/v1/posts/export';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `postsControllerExport()` instead.
   *
   * This method doesn't expect any request body.
   */
  postsControllerExport$Response(params?: PostsControllerExport$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = postsControllerExport(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `postsControllerExport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  postsControllerExport(params?: PostsControllerExport$Params, context?: HttpContext): Promise<void> {
    const resp = this.postsControllerExport$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `postsControllerFindOne()` */
  static readonly PostsControllerFindOnePath = '/api/v1/posts/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `postsControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  postsControllerFindOne$Response(params: PostsControllerFindOne$Params, context?: HttpContext): Promise<StrictHttpResponse<PostResponse>> {
    const obs = postsControllerFindOne(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `postsControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  postsControllerFindOne(params: PostsControllerFindOne$Params, context?: HttpContext): Promise<PostResponse> {
    const resp = this.postsControllerFindOne$Response(params, context);
    return resp.then((r: StrictHttpResponse<PostResponse>): PostResponse => r.body);
  }

  /** Path part for operation `postsControllerDelete()` */
  static readonly PostsControllerDeletePath = '/api/v1/posts/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `postsControllerDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  postsControllerDelete$Response(params: PostsControllerDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = postsControllerDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `postsControllerDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  postsControllerDelete(params: PostsControllerDelete$Params, context?: HttpContext): Promise<void> {
    const resp = this.postsControllerDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `postsControllerUpdate()` */
  static readonly PostsControllerUpdatePath = '/api/v1/posts/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `postsControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  postsControllerUpdate$Response(params: PostsControllerUpdate$Params, context?: HttpContext): Promise<StrictHttpResponse<PostResponse>> {
    const obs = postsControllerUpdate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `postsControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  postsControllerUpdate(params: PostsControllerUpdate$Params, context?: HttpContext): Promise<PostResponse> {
    const resp = this.postsControllerUpdate$Response(params, context);
    return resp.then((r: StrictHttpResponse<PostResponse>): PostResponse => r.body);
  }

  /** Path part for operation `postsControllerRestore()` */
  static readonly PostsControllerRestorePath = '/api/v1/posts/{id}/restore';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `postsControllerRestore()` instead.
   *
   * This method doesn't expect any request body.
   */
  postsControllerRestore$Response(params: PostsControllerRestore$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = postsControllerRestore(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `postsControllerRestore$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  postsControllerRestore(params: PostsControllerRestore$Params, context?: HttpContext): Promise<any> {
    const resp = this.postsControllerRestore$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `postsControllerBulkDelete()` */
  static readonly PostsControllerBulkDeletePath = '/api/v1/posts/bulk-delete';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `postsControllerBulkDelete()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  postsControllerBulkDelete$Response(params: PostsControllerBulkDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = postsControllerBulkDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `postsControllerBulkDelete$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  postsControllerBulkDelete(params: PostsControllerBulkDelete$Params, context?: HttpContext): Promise<any> {
    const resp = this.postsControllerBulkDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `postsControllerBulkRestore()` */
  static readonly PostsControllerBulkRestorePath = '/api/v1/posts/bulk-restore';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `postsControllerBulkRestore()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  postsControllerBulkRestore$Response(params: PostsControllerBulkRestore$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = postsControllerBulkRestore(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `postsControllerBulkRestore$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  postsControllerBulkRestore(params: PostsControllerBulkRestore$Params, context?: HttpContext): Promise<any> {
    const resp = this.postsControllerBulkRestore$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

}
