/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CreateAppointmentResponse } from '../models/create-appointment-response';
import { publicAppointmentsControllerSubmit } from '../fn/public/public-appointments-controller-submit';
import { PublicAppointmentsControllerSubmit$Params } from '../fn/public/public-appointments-controller-submit';

@Injectable({ providedIn: 'root' })
export class PublicService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `publicAppointmentsControllerSubmit()` */
  static readonly PublicAppointmentsControllerSubmitPath = '/api/v1/public/appointments';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publicAppointmentsControllerSubmit()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  publicAppointmentsControllerSubmit$Response(params: PublicAppointmentsControllerSubmit$Params, context?: HttpContext): Promise<StrictHttpResponse<CreateAppointmentResponse>> {
    const obs = publicAppointmentsControllerSubmit(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publicAppointmentsControllerSubmit$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  publicAppointmentsControllerSubmit(params: PublicAppointmentsControllerSubmit$Params, context?: HttpContext): Promise<CreateAppointmentResponse> {
    const resp = this.publicAppointmentsControllerSubmit$Response(params, context);
    return resp.then((r: StrictHttpResponse<CreateAppointmentResponse>): CreateAppointmentResponse => r.body);
  }

}
