/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { RoleResponseDto } from '../models/role-response-dto';
import { rolesControllerAttachPermission } from '../fn/roles/roles-controller-attach-permission';
import { RolesControllerAttachPermission$Params } from '../fn/roles/roles-controller-attach-permission';
import { rolesControllerBulkDelete } from '../fn/roles/roles-controller-bulk-delete';
import { RolesControllerBulkDelete$Params } from '../fn/roles/roles-controller-bulk-delete';
import { rolesControllerBulkRestore } from '../fn/roles/roles-controller-bulk-restore';
import { RolesControllerBulkRestore$Params } from '../fn/roles/roles-controller-bulk-restore';
import { rolesControllerCreate } from '../fn/roles/roles-controller-create';
import { RolesControllerCreate$Params } from '../fn/roles/roles-controller-create';
import { rolesControllerDetachPermission } from '../fn/roles/roles-controller-detach-permission';
import { RolesControllerDetachPermission$Params } from '../fn/roles/roles-controller-detach-permission';
import { rolesControllerExport } from '../fn/roles/roles-controller-export';
import { RolesControllerExport$Params } from '../fn/roles/roles-controller-export';
import { rolesControllerFindAll } from '../fn/roles/roles-controller-find-all';
import { RolesControllerFindAll$Params } from '../fn/roles/roles-controller-find-all';
import { rolesControllerFindOne } from '../fn/roles/roles-controller-find-one';
import { RolesControllerFindOne$Params } from '../fn/roles/roles-controller-find-one';
import { rolesControllerFindTrash } from '../fn/roles/roles-controller-find-trash';
import { RolesControllerFindTrash$Params } from '../fn/roles/roles-controller-find-trash';
import { rolesControllerRemove } from '../fn/roles/roles-controller-remove';
import { RolesControllerRemove$Params } from '../fn/roles/roles-controller-remove';
import { rolesControllerRestore } from '../fn/roles/roles-controller-restore';
import { RolesControllerRestore$Params } from '../fn/roles/roles-controller-restore';
import { rolesControllerUpdate } from '../fn/roles/roles-controller-update';
import { RolesControllerUpdate$Params } from '../fn/roles/roles-controller-update';

@Injectable({ providedIn: 'root' })
export class RolesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `rolesControllerFindAll()` */
  static readonly RolesControllerFindAllPath = '/api/v1/roles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rolesControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesControllerFindAll$Response(params?: RolesControllerFindAll$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<RoleResponseDto>>> {
    const obs = rolesControllerFindAll(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rolesControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesControllerFindAll(params?: RolesControllerFindAll$Params, context?: HttpContext): Promise<Array<RoleResponseDto>> {
    const resp = this.rolesControllerFindAll$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<RoleResponseDto>>): Array<RoleResponseDto> => r.body);
  }

  /** Path part for operation `rolesControllerCreate()` */
  static readonly RolesControllerCreatePath = '/api/v1/roles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rolesControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  rolesControllerCreate$Response(params: RolesControllerCreate$Params, context?: HttpContext): Promise<StrictHttpResponse<RoleResponseDto>> {
    const obs = rolesControllerCreate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rolesControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  rolesControllerCreate(params: RolesControllerCreate$Params, context?: HttpContext): Promise<RoleResponseDto> {
    const resp = this.rolesControllerCreate$Response(params, context);
    return resp.then((r: StrictHttpResponse<RoleResponseDto>): RoleResponseDto => r.body);
  }

  /** Path part for operation `rolesControllerFindTrash()` */
  static readonly RolesControllerFindTrashPath = '/api/v1/roles/trash';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rolesControllerFindTrash()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesControllerFindTrash$Response(params?: RolesControllerFindTrash$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<RoleResponseDto>>> {
    const obs = rolesControllerFindTrash(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rolesControllerFindTrash$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesControllerFindTrash(params?: RolesControllerFindTrash$Params, context?: HttpContext): Promise<Array<RoleResponseDto>> {
    const resp = this.rolesControllerFindTrash$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<RoleResponseDto>>): Array<RoleResponseDto> => r.body);
  }

  /** Path part for operation `rolesControllerExport()` */
  static readonly RolesControllerExportPath = '/api/v1/roles/export';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rolesControllerExport()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesControllerExport$Response(params: RolesControllerExport$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = rolesControllerExport(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rolesControllerExport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesControllerExport(params: RolesControllerExport$Params, context?: HttpContext): Promise<any> {
    const resp = this.rolesControllerExport$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `rolesControllerFindOne()` */
  static readonly RolesControllerFindOnePath = '/api/v1/roles/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rolesControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesControllerFindOne$Response(params: RolesControllerFindOne$Params, context?: HttpContext): Promise<StrictHttpResponse<RoleResponseDto>> {
    const obs = rolesControllerFindOne(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rolesControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesControllerFindOne(params: RolesControllerFindOne$Params, context?: HttpContext): Promise<RoleResponseDto> {
    const resp = this.rolesControllerFindOne$Response(params, context);
    return resp.then((r: StrictHttpResponse<RoleResponseDto>): RoleResponseDto => r.body);
  }

  /** Path part for operation `rolesControllerRemove()` */
  static readonly RolesControllerRemovePath = '/api/v1/roles/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rolesControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesControllerRemove$Response(params: RolesControllerRemove$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = rolesControllerRemove(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rolesControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesControllerRemove(params: RolesControllerRemove$Params, context?: HttpContext): Promise<void> {
    const resp = this.rolesControllerRemove$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `rolesControllerUpdate()` */
  static readonly RolesControllerUpdatePath = '/api/v1/roles/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rolesControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  rolesControllerUpdate$Response(params: RolesControllerUpdate$Params, context?: HttpContext): Promise<StrictHttpResponse<RoleResponseDto>> {
    const obs = rolesControllerUpdate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rolesControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  rolesControllerUpdate(params: RolesControllerUpdate$Params, context?: HttpContext): Promise<RoleResponseDto> {
    const resp = this.rolesControllerUpdate$Response(params, context);
    return resp.then((r: StrictHttpResponse<RoleResponseDto>): RoleResponseDto => r.body);
  }

  /** Path part for operation `rolesControllerRestore()` */
  static readonly RolesControllerRestorePath = '/api/v1/roles/{id}/restore';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rolesControllerRestore()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesControllerRestore$Response(params: RolesControllerRestore$Params, context?: HttpContext): Promise<StrictHttpResponse<RoleResponseDto>> {
    const obs = rolesControllerRestore(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rolesControllerRestore$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesControllerRestore(params: RolesControllerRestore$Params, context?: HttpContext): Promise<RoleResponseDto> {
    const resp = this.rolesControllerRestore$Response(params, context);
    return resp.then((r: StrictHttpResponse<RoleResponseDto>): RoleResponseDto => r.body);
  }

  /** Path part for operation `rolesControllerAttachPermission()` */
  static readonly RolesControllerAttachPermissionPath = '/api/v1/roles/{id}/permissions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rolesControllerAttachPermission()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  rolesControllerAttachPermission$Response(params: RolesControllerAttachPermission$Params, context?: HttpContext): Promise<StrictHttpResponse<RoleResponseDto>> {
    const obs = rolesControllerAttachPermission(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rolesControllerAttachPermission$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  rolesControllerAttachPermission(params: RolesControllerAttachPermission$Params, context?: HttpContext): Promise<RoleResponseDto> {
    const resp = this.rolesControllerAttachPermission$Response(params, context);
    return resp.then((r: StrictHttpResponse<RoleResponseDto>): RoleResponseDto => r.body);
  }

  /** Path part for operation `rolesControllerDetachPermission()` */
  static readonly RolesControllerDetachPermissionPath = '/api/v1/roles/{id}/permissions/{permissionId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rolesControllerDetachPermission()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesControllerDetachPermission$Response(params: RolesControllerDetachPermission$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = rolesControllerDetachPermission(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rolesControllerDetachPermission$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  rolesControllerDetachPermission(params: RolesControllerDetachPermission$Params, context?: HttpContext): Promise<void> {
    const resp = this.rolesControllerDetachPermission$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `rolesControllerBulkDelete()` */
  static readonly RolesControllerBulkDeletePath = '/api/v1/roles/bulk-delete';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rolesControllerBulkDelete()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  rolesControllerBulkDelete$Response(params: RolesControllerBulkDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = rolesControllerBulkDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rolesControllerBulkDelete$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  rolesControllerBulkDelete(params: RolesControllerBulkDelete$Params, context?: HttpContext): Promise<any> {
    const resp = this.rolesControllerBulkDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `rolesControllerBulkRestore()` */
  static readonly RolesControllerBulkRestorePath = '/api/v1/roles/bulk-restore';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rolesControllerBulkRestore()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  rolesControllerBulkRestore$Response(params: RolesControllerBulkRestore$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = rolesControllerBulkRestore(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rolesControllerBulkRestore$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  rolesControllerBulkRestore(params: RolesControllerBulkRestore$Params, context?: HttpContext): Promise<any> {
    const resp = this.rolesControllerBulkRestore$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

}
