/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { GeneratePostJobResultDto } from '../models/generate-post-job-result-dto';
import { PaginatedSocialMediaResponse } from '../models/paginated-social-media-response';
import { socialMediaControllerBulkDelete } from '../fn/social-media/social-media-controller-bulk-delete';
import { SocialMediaControllerBulkDelete$Params } from '../fn/social-media/social-media-controller-bulk-delete';
import { socialMediaControllerDownloadZip } from '../fn/social-media/social-media-controller-download-zip';
import { SocialMediaControllerDownloadZip$Params } from '../fn/social-media/social-media-controller-download-zip';
import { socialMediaControllerExport } from '../fn/social-media/social-media-controller-export';
import { SocialMediaControllerExport$Params } from '../fn/social-media/social-media-controller-export';
import { socialMediaControllerFindOne } from '../fn/social-media/social-media-controller-find-one';
import { SocialMediaControllerFindOne$Params } from '../fn/social-media/social-media-controller-find-one';
import { socialMediaControllerFindTopics } from '../fn/social-media/social-media-controller-find-topics';
import { SocialMediaControllerFindTopics$Params } from '../fn/social-media/social-media-controller-find-topics';
import { socialMediaControllerGenerate } from '../fn/social-media/social-media-controller-generate';
import { SocialMediaControllerGenerate$Params } from '../fn/social-media/social-media-controller-generate';
import { socialMediaControllerList } from '../fn/social-media/social-media-controller-list';
import { SocialMediaControllerList$Params } from '../fn/social-media/social-media-controller-list';
import { socialMediaControllerRemove } from '../fn/social-media/social-media-controller-remove';
import { SocialMediaControllerRemove$Params } from '../fn/social-media/social-media-controller-remove';
import { SocialMediaGenerationResponse } from '../models/social-media-generation-response';
import { SocialMediaTopicResponse } from '../models/social-media-topic-response';

@Injectable({ providedIn: 'root' })
export class SocialMediaService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `socialMediaControllerFindTopics()` */
  static readonly SocialMediaControllerFindTopicsPath = '/api/v1/social-media/generate-topics';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `socialMediaControllerFindTopics()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  socialMediaControllerFindTopics$Response(params: SocialMediaControllerFindTopics$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<SocialMediaTopicResponse>>> {
    const obs = socialMediaControllerFindTopics(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `socialMediaControllerFindTopics$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  socialMediaControllerFindTopics(params: SocialMediaControllerFindTopics$Params, context?: HttpContext): Promise<Array<SocialMediaTopicResponse>> {
    const resp = this.socialMediaControllerFindTopics$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<SocialMediaTopicResponse>>): Array<SocialMediaTopicResponse> => r.body);
  }

  /** Path part for operation `socialMediaControllerGenerate()` */
  static readonly SocialMediaControllerGeneratePath = '/api/v1/social-media/generate-content';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `socialMediaControllerGenerate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  socialMediaControllerGenerate$Response(params: SocialMediaControllerGenerate$Params, context?: HttpContext): Promise<StrictHttpResponse<GeneratePostJobResultDto>> {
    const obs = socialMediaControllerGenerate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `socialMediaControllerGenerate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  socialMediaControllerGenerate(params: SocialMediaControllerGenerate$Params, context?: HttpContext): Promise<GeneratePostJobResultDto> {
    const resp = this.socialMediaControllerGenerate$Response(params, context);
    return resp.then((r: StrictHttpResponse<GeneratePostJobResultDto>): GeneratePostJobResultDto => r.body);
  }

  /** Path part for operation `socialMediaControllerList()` */
  static readonly SocialMediaControllerListPath = '/api/v1/social-media';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `socialMediaControllerList()` instead.
   *
   * This method doesn't expect any request body.
   */
  socialMediaControllerList$Response(params?: SocialMediaControllerList$Params, context?: HttpContext): Promise<StrictHttpResponse<PaginatedSocialMediaResponse>> {
    const obs = socialMediaControllerList(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `socialMediaControllerList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  socialMediaControllerList(params?: SocialMediaControllerList$Params, context?: HttpContext): Promise<PaginatedSocialMediaResponse> {
    const resp = this.socialMediaControllerList$Response(params, context);
    return resp.then((r: StrictHttpResponse<PaginatedSocialMediaResponse>): PaginatedSocialMediaResponse => r.body);
  }

  /** Path part for operation `socialMediaControllerFindOne()` */
  static readonly SocialMediaControllerFindOnePath = '/api/v1/social-media/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `socialMediaControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  socialMediaControllerFindOne$Response(params: SocialMediaControllerFindOne$Params, context?: HttpContext): Promise<StrictHttpResponse<SocialMediaGenerationResponse>> {
    const obs = socialMediaControllerFindOne(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `socialMediaControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  socialMediaControllerFindOne(params: SocialMediaControllerFindOne$Params, context?: HttpContext): Promise<SocialMediaGenerationResponse> {
    const resp = this.socialMediaControllerFindOne$Response(params, context);
    return resp.then((r: StrictHttpResponse<SocialMediaGenerationResponse>): SocialMediaGenerationResponse => r.body);
  }

  /** Path part for operation `socialMediaControllerRemove()` */
  static readonly SocialMediaControllerRemovePath = '/api/v1/social-media/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `socialMediaControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  socialMediaControllerRemove$Response(params: SocialMediaControllerRemove$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = socialMediaControllerRemove(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `socialMediaControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  socialMediaControllerRemove(params: SocialMediaControllerRemove$Params, context?: HttpContext): Promise<void> {
    const resp = this.socialMediaControllerRemove$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `socialMediaControllerBulkDelete()` */
  static readonly SocialMediaControllerBulkDeletePath = '/api/v1/social-media/bulk-delete';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `socialMediaControllerBulkDelete()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  socialMediaControllerBulkDelete$Response(params: SocialMediaControllerBulkDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'count'?: number;
}>> {
    const obs = socialMediaControllerBulkDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `socialMediaControllerBulkDelete$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  socialMediaControllerBulkDelete(params: SocialMediaControllerBulkDelete$Params, context?: HttpContext): Promise<{
'count'?: number;
}> {
    const resp = this.socialMediaControllerBulkDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'count'?: number;
}>): {
'count'?: number;
} => r.body);
  }

  /** Path part for operation `socialMediaControllerExport()` */
  static readonly SocialMediaControllerExportPath = '/api/v1/social-media/export';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `socialMediaControllerExport()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  socialMediaControllerExport$Response(params: SocialMediaControllerExport$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = socialMediaControllerExport(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `socialMediaControllerExport$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  socialMediaControllerExport(params: SocialMediaControllerExport$Params, context?: HttpContext): Promise<void> {
    const resp = this.socialMediaControllerExport$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `socialMediaControllerDownloadZip()` */
  static readonly SocialMediaControllerDownloadZipPath = '/api/v1/social-media/{id}/download-zip';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `socialMediaControllerDownloadZip()` instead.
   *
   * This method doesn't expect any request body.
   */
  socialMediaControllerDownloadZip$Response(params: SocialMediaControllerDownloadZip$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = socialMediaControllerDownloadZip(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `socialMediaControllerDownloadZip$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  socialMediaControllerDownloadZip(params: SocialMediaControllerDownloadZip$Params, context?: HttpContext): Promise<void> {
    const resp = this.socialMediaControllerDownloadZip$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
