/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { UserPermissionResponseDto } from '../models/user-permission-response-dto';
import { userPermissionsControllerList } from '../fn/user-permissions/user-permissions-controller-list';
import { UserPermissionsControllerList$Params } from '../fn/user-permissions/user-permissions-controller-list';
import { userPermissionsControllerRemove } from '../fn/user-permissions/user-permissions-controller-remove';
import { UserPermissionsControllerRemove$Params } from '../fn/user-permissions/user-permissions-controller-remove';
import { userPermissionsControllerUpsert } from '../fn/user-permissions/user-permissions-controller-upsert';
import { UserPermissionsControllerUpsert$Params } from '../fn/user-permissions/user-permissions-controller-upsert';

@Injectable({ providedIn: 'root' })
export class UserPermissionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `userPermissionsControllerList()` */
  static readonly UserPermissionsControllerListPath = '/api/v1/users/{userId}/permissions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userPermissionsControllerList()` instead.
   *
   * This method doesn't expect any request body.
   */
  userPermissionsControllerList$Response(params: UserPermissionsControllerList$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UserPermissionResponseDto>>> {
    const obs = userPermissionsControllerList(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userPermissionsControllerList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userPermissionsControllerList(params: UserPermissionsControllerList$Params, context?: HttpContext): Promise<Array<UserPermissionResponseDto>> {
    const resp = this.userPermissionsControllerList$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UserPermissionResponseDto>>): Array<UserPermissionResponseDto> => r.body);
  }

  /** Path part for operation `userPermissionsControllerUpsert()` */
  static readonly UserPermissionsControllerUpsertPath = '/api/v1/users/{userId}/permissions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userPermissionsControllerUpsert()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userPermissionsControllerUpsert$Response(params: UserPermissionsControllerUpsert$Params, context?: HttpContext): Promise<StrictHttpResponse<UserPermissionResponseDto>> {
    const obs = userPermissionsControllerUpsert(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userPermissionsControllerUpsert$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userPermissionsControllerUpsert(params: UserPermissionsControllerUpsert$Params, context?: HttpContext): Promise<UserPermissionResponseDto> {
    const resp = this.userPermissionsControllerUpsert$Response(params, context);
    return resp.then((r: StrictHttpResponse<UserPermissionResponseDto>): UserPermissionResponseDto => r.body);
  }

  /** Path part for operation `userPermissionsControllerRemove()` */
  static readonly UserPermissionsControllerRemovePath = '/api/v1/users/{userId}/permissions/{permissionId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userPermissionsControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  userPermissionsControllerRemove$Response(params: UserPermissionsControllerRemove$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = userPermissionsControllerRemove(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userPermissionsControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userPermissionsControllerRemove(params: UserPermissionsControllerRemove$Params, context?: HttpContext): Promise<void> {
    const resp = this.userPermissionsControllerRemove$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
