/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { MessageResponse } from '../models/message-response';
import { UserListResponse } from '../models/user-list-response';
import { UserResponse } from '../models/user-response';
import { usersControllerBulkDelete } from '../fn/users/users-controller-bulk-delete';
import { UsersControllerBulkDelete$Params } from '../fn/users/users-controller-bulk-delete';
import { usersControllerBulkRestore } from '../fn/users/users-controller-bulk-restore';
import { UsersControllerBulkRestore$Params } from '../fn/users/users-controller-bulk-restore';
import { usersControllerChangePassword } from '../fn/users/users-controller-change-password';
import { UsersControllerChangePassword$Params } from '../fn/users/users-controller-change-password';
import { usersControllerCheckEmail } from '../fn/users/users-controller-check-email';
import { UsersControllerCheckEmail$Params } from '../fn/users/users-controller-check-email';
import { usersControllerCheckUsername } from '../fn/users/users-controller-check-username';
import { UsersControllerCheckUsername$Params } from '../fn/users/users-controller-check-username';
import { usersControllerCreate } from '../fn/users/users-controller-create';
import { UsersControllerCreate$Params } from '../fn/users/users-controller-create';
import { usersControllerExport } from '../fn/users/users-controller-export';
import { UsersControllerExport$Params } from '../fn/users/users-controller-export';
import { usersControllerFindAll } from '../fn/users/users-controller-find-all';
import { UsersControllerFindAll$Params } from '../fn/users/users-controller-find-all';
import { usersControllerFindOne } from '../fn/users/users-controller-find-one';
import { UsersControllerFindOne$Params } from '../fn/users/users-controller-find-one';
import { usersControllerRemove } from '../fn/users/users-controller-remove';
import { UsersControllerRemove$Params } from '../fn/users/users-controller-remove';
import { usersControllerRequestPasswordChange } from '../fn/users/users-controller-request-password-change';
import { UsersControllerRequestPasswordChange$Params } from '../fn/users/users-controller-request-password-change';
import { usersControllerSetupPassword } from '../fn/users/users-controller-setup-password';
import { UsersControllerSetupPassword$Params } from '../fn/users/users-controller-setup-password';
import { usersControllerUpdate } from '../fn/users/users-controller-update';
import { UsersControllerUpdate$Params } from '../fn/users/users-controller-update';

@Injectable({ providedIn: 'root' })
export class UsersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `usersControllerFindAll()` */
  static readonly UsersControllerFindAllPath = '/api/v1/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerFindAll$Response(params?: UsersControllerFindAll$Params, context?: HttpContext): Promise<StrictHttpResponse<UserListResponse>> {
    const obs = usersControllerFindAll(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerFindAll(params?: UsersControllerFindAll$Params, context?: HttpContext): Promise<UserListResponse> {
    const resp = this.usersControllerFindAll$Response(params, context);
    return resp.then((r: StrictHttpResponse<UserListResponse>): UserListResponse => r.body);
  }

  /** Path part for operation `usersControllerCreate()` */
  static readonly UsersControllerCreatePath = '/api/v1/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerCreate$Response(params: UsersControllerCreate$Params, context?: HttpContext): Promise<StrictHttpResponse<UserResponse>> {
    const obs = usersControllerCreate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerCreate(params: UsersControllerCreate$Params, context?: HttpContext): Promise<UserResponse> {
    const resp = this.usersControllerCreate$Response(params, context);
    return resp.then((r: StrictHttpResponse<UserResponse>): UserResponse => r.body);
  }

  /** Path part for operation `usersControllerSetupPassword()` */
  static readonly UsersControllerSetupPasswordPath = '/api/v1/users/setup-password';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerSetupPassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerSetupPassword$Response(params: UsersControllerSetupPassword$Params, context?: HttpContext): Promise<StrictHttpResponse<MessageResponse>> {
    const obs = usersControllerSetupPassword(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerSetupPassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerSetupPassword(params: UsersControllerSetupPassword$Params, context?: HttpContext): Promise<MessageResponse> {
    const resp = this.usersControllerSetupPassword$Response(params, context);
    return resp.then((r: StrictHttpResponse<MessageResponse>): MessageResponse => r.body);
  }

  /** Path part for operation `usersControllerRequestPasswordChange()` */
  static readonly UsersControllerRequestPasswordChangePath = '/api/v1/users/request-password-change';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerRequestPasswordChange()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerRequestPasswordChange$Response(params: UsersControllerRequestPasswordChange$Params, context?: HttpContext): Promise<StrictHttpResponse<MessageResponse>> {
    const obs = usersControllerRequestPasswordChange(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerRequestPasswordChange$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerRequestPasswordChange(params: UsersControllerRequestPasswordChange$Params, context?: HttpContext): Promise<MessageResponse> {
    const resp = this.usersControllerRequestPasswordChange$Response(params, context);
    return resp.then((r: StrictHttpResponse<MessageResponse>): MessageResponse => r.body);
  }

  /** Path part for operation `usersControllerChangePassword()` */
  static readonly UsersControllerChangePasswordPath = '/api/v1/users/change-password';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerChangePassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerChangePassword$Response(params: UsersControllerChangePassword$Params, context?: HttpContext): Promise<StrictHttpResponse<MessageResponse>> {
    const obs = usersControllerChangePassword(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerChangePassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerChangePassword(params: UsersControllerChangePassword$Params, context?: HttpContext): Promise<MessageResponse> {
    const resp = this.usersControllerChangePassword$Response(params, context);
    return resp.then((r: StrictHttpResponse<MessageResponse>): MessageResponse => r.body);
  }

  /** Path part for operation `usersControllerExport()` */
  static readonly UsersControllerExportPath = '/api/v1/users/export';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerExport()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerExport$Response(params?: UsersControllerExport$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = usersControllerExport(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerExport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerExport(params?: UsersControllerExport$Params, context?: HttpContext): Promise<any> {
    const resp = this.usersControllerExport$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `usersControllerCheckEmail()` */
  static readonly UsersControllerCheckEmailPath = '/api/v1/users/check/email';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerCheckEmail()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerCheckEmail$Response(params: UsersControllerCheckEmail$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'exists'?: boolean;
}>> {
    const obs = usersControllerCheckEmail(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerCheckEmail$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerCheckEmail(params: UsersControllerCheckEmail$Params, context?: HttpContext): Promise<{
'exists'?: boolean;
}> {
    const resp = this.usersControllerCheckEmail$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'exists'?: boolean;
}>): {
'exists'?: boolean;
} => r.body);
  }

  /** Path part for operation `usersControllerCheckUsername()` */
  static readonly UsersControllerCheckUsernamePath = '/api/v1/users/check/username';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerCheckUsername()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerCheckUsername$Response(params: UsersControllerCheckUsername$Params, context?: HttpContext): Promise<StrictHttpResponse<{
'exists'?: boolean;
}>> {
    const obs = usersControllerCheckUsername(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerCheckUsername$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerCheckUsername(params: UsersControllerCheckUsername$Params, context?: HttpContext): Promise<{
'exists'?: boolean;
}> {
    const resp = this.usersControllerCheckUsername$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
'exists'?: boolean;
}>): {
'exists'?: boolean;
} => r.body);
  }

  /** Path part for operation `usersControllerFindOne()` */
  static readonly UsersControllerFindOnePath = '/api/v1/users/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerFindOne$Response(params: UsersControllerFindOne$Params, context?: HttpContext): Promise<StrictHttpResponse<UserResponse>> {
    const obs = usersControllerFindOne(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerFindOne(params: UsersControllerFindOne$Params, context?: HttpContext): Promise<UserResponse> {
    const resp = this.usersControllerFindOne$Response(params, context);
    return resp.then((r: StrictHttpResponse<UserResponse>): UserResponse => r.body);
  }

  /** Path part for operation `usersControllerRemove()` */
  static readonly UsersControllerRemovePath = '/api/v1/users/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerRemove$Response(params: UsersControllerRemove$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = usersControllerRemove(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  usersControllerRemove(params: UsersControllerRemove$Params, context?: HttpContext): Promise<void> {
    const resp = this.usersControllerRemove$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `usersControllerUpdate()` */
  static readonly UsersControllerUpdatePath = '/api/v1/users/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerUpdate$Response(params: UsersControllerUpdate$Params, context?: HttpContext): Promise<StrictHttpResponse<UserResponse>> {
    const obs = usersControllerUpdate(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerUpdate(params: UsersControllerUpdate$Params, context?: HttpContext): Promise<UserResponse> {
    const resp = this.usersControllerUpdate$Response(params, context);
    return resp.then((r: StrictHttpResponse<UserResponse>): UserResponse => r.body);
  }

  /** Path part for operation `usersControllerBulkDelete()` */
  static readonly UsersControllerBulkDeletePath = '/api/v1/users/bulk-delete';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerBulkDelete()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerBulkDelete$Response(params: UsersControllerBulkDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = usersControllerBulkDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerBulkDelete$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerBulkDelete(params: UsersControllerBulkDelete$Params, context?: HttpContext): Promise<any> {
    const resp = this.usersControllerBulkDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

  /** Path part for operation `usersControllerBulkRestore()` */
  static readonly UsersControllerBulkRestorePath = '/api/v1/users/bulk-restore';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `usersControllerBulkRestore()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerBulkRestore$Response(params: UsersControllerBulkRestore$Params, context?: HttpContext): Promise<StrictHttpResponse<any>> {
    const obs = usersControllerBulkRestore(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `usersControllerBulkRestore$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  usersControllerBulkRestore(params: UsersControllerBulkRestore$Params, context?: HttpContext): Promise<any> {
    const resp = this.usersControllerBulkRestore$Response(params, context);
    return resp.then((r: StrictHttpResponse<any>): any => r.body);
  }

}
