/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyDataResponse } from '../../models/company-data-response';

export interface CompanyDataControllerFindPublic$Params {
}

export function companyDataControllerFindPublic(http: HttpClient, rootUrl: string, params?: CompanyDataControllerFindPublic$Params, context?: HttpContext): Observable<StrictHttpResponse<CompanyDataResponse>> {
  const rb = new RequestBuilder(rootUrl, companyDataControllerFindPublic.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompanyDataResponse>;
    })
  );
}

companyDataControllerFindPublic.PATH = '/api/v1/company-data/public';
