/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GeneratePostDto } from '../../models/generate-post-dto';
import { GeneratePostJobResultDto } from '../../models/generate-post-job-result-dto';

export interface SocialMediaControllerGenerate$Params {
      body: GeneratePostDto
}

export function socialMediaControllerGenerate(http: HttpClient, rootUrl: string, params: SocialMediaControllerGenerate$Params, context?: HttpContext): Observable<StrictHttpResponse<GeneratePostJobResultDto>> {
  const rb = new RequestBuilder(rootUrl, socialMediaControllerGenerate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GeneratePostJobResultDto>;
    })
  );
}

socialMediaControllerGenerate.PATH = '/api/v1/social-media/generate-content';
