/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FindTopicsDto } from '../../models/find-topics-dto';
import { SocialMediaTopicResponse } from '../../models/social-media-topic-response';

export interface SocialMediaControllerFindTopics$Params {
      body: FindTopicsDto
}

export function socialMediaControllerFindTopics(http: HttpClient, rootUrl: string, params: SocialMediaControllerFindTopics$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SocialMediaTopicResponse>>> {
  const rb = new RequestBuilder(rootUrl, socialMediaControllerFindTopics.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SocialMediaTopicResponse>>;
    })
  );
}

socialMediaControllerFindTopics.PATH = '/api/v1/social-media/generate-topics';
