/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedSocialMediaResponse } from '../../models/paginated-social-media-response';

export interface SocialMediaControllerList$Params {
  page?: number;
  limit?: number;
  niche?: string;
  language?: string;
  network?: 'facebook' | 'instagram' | 'tiktok' | 'linkedin' | 'twitter';
  start_date?: string;
  end_date?: string;
}

export function socialMediaControllerList(http: HttpClient, rootUrl: string, params?: SocialMediaControllerList$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedSocialMediaResponse>> {
  const rb = new RequestBuilder(rootUrl, socialMediaControllerList.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
    rb.query('niche', params.niche, {});
    rb.query('language', params.language, {});
    rb.query('network', params.network, {});
    rb.query('start_date', params.start_date, {});
    rb.query('end_date', params.end_date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedSocialMediaResponse>;
    })
  );
}

socialMediaControllerList.PATH = '/api/v1/social-media';
