/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SocialMediaGenerationResponse } from '../../models/social-media-generation-response';

export interface SocialMediaControllerFindOne$Params {

/**
 * Social media generation UUID
 */
  id: string;
}

export function socialMediaControllerFindOne(http: HttpClient, rootUrl: string, params: SocialMediaControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<SocialMediaGenerationResponse>> {
  const rb = new RequestBuilder(rootUrl, socialMediaControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SocialMediaGenerationResponse>;
    })
  );
}

socialMediaControllerFindOne.PATH = '/api/v1/social-media/{id}';
